# Verified 200-company AITI universe. Do not invent names.
# Format: name, domain, source, official_url
UNIVERSE = [
    ("01.AI", "01.ai", "arena-org", "https://www.01.ai/"),
    ("7AI", "7ai.com", "cb-insights-ai-100-2026", "https://7ai.com/"),
    ("Aaru", "aaru.com", "cb-insights-ai-100-2026", "https://aaru.com/"),
    ("Abridge", "abridge.com", "forbes-ai-50-2026", "https://www.abridge.com/"),
    ("Accordance", "accordance.com", "forbes-ai-50-brink-2026", "https://accordance.com/"),
    ("Actively AI", "actively.ai", "cb-insights-ai-100-2026", "https://www.actively.ai/"),
    ("Advanced Machine Intelligence", "amilabs.xyz", "forbes-ai-50-brink-2026", "https://amilabs.xyz/"),
    ("AgentSmyth", "agentsmyth.com", "cb-insights-ai-100-2026", "https://agentsmyth.com/"),
    ("AI21", "ai21.com", "openrouter-provider", "https://www.ai21.com/"),
    ("Alex", "alex.com", "cb-insights-ai-100-2026", "https://www.alex.com/"),
    ("Alibaba", "alibabacloud.com", "arena-org", "https://www.alibabacloud.com/en"),
    ("Allen Institute for AI", "allenai.org", "arena-org", "https://allenai.org/"),
    ("Amazon", "amazon.com", "arena-org", "https://aws.amazon.com/ai/"),
    ("Anam", "anam.ai", "cb-insights-ai-100-2026", "https://anam.ai/"),
    ("Ankar", "ankar.ai", "cb-insights-ai-100-2026", "https://ankar.ai/"),
    ("Anthropic", "anthropic.com", "forbes-ai-50-2026", "https://www.anthropic.com/"),
    ("Antithesis", "antithesis.com", "cb-insights-ai-100-2026", "https://antithesis.com/"),
    ("Apple", "apple.com", "hugging-face-org", "https://www.apple.com/"),
    ("Applied Intuition", "appliedintuition.com", "forbes-ai-50-2026", "https://www.appliedintuition.com/"),
    ("Arcee AI", "arcee.ai", "openrouter-provider", "https://www.arcee.ai/"),
    ("Assort Health", "assorthealth.com", "cb-insights-ai-100-2026", "https://www.assorthealth.com/"),
    ("Atomic Canyon", "atomiccanyon.com", "cb-insights-ai-100-2026", "https://atomiccanyon.com/"),
    ("Augmentus", "augmentus.tech", "cb-insights-ai-100-2026", "https://www.augmentus.tech/"),
    ("Aurascape", "aurascape.ai", "cb-insights-ai-100-2026", "https://aurascape.ai/"),
    ("Avantos", "avantos.ai", "cb-insights-ai-100-2026", "https://avantos.ai/"),
    ("Axiom", "axiommath.ai", "forbes-ai-50-brink-2026", "https://axiommath.ai/"),
    ("Baidu", "baidu.com", "arena-org", "https://www.baidu.com/"),
    ("Baseten", "baseten.co", "forbes-ai-50-2026", "https://www.baseten.co/"),
    ("Black Forest Labs", "bfl.ai", "forbes-ai-50-2026", "https://bfl.ai/"),
    ("Blue Water Autonomy", "blw.ai", "cb-insights-ai-100-2026", "https://www.blw.ai/"),
    ("Bluefish", "bluefishai.com", "cb-insights-ai-100-2026", "https://www.bluefishai.com/"),
    ("Boltz", "boltz.bio", "cb-insights-ai-100-2026", "https://boltz.bio/"),
    ("BOS Semiconductors", "bos-semi.com", "cb-insights-ai-100-2026", "https://www.bos-semi.com/"),
    ("BRIA AI", "bria.ai", "hugging-face-org", "https://bria.ai/"),
    ("Browser Use", "browser-use.com", "cb-insights-ai-100-2026", "https://browser-use.com/"),
    ("ByteDance", "bytedance.com", "arena-org", "https://www.bytedance.com/"),
    ("Cerebras", "cerebras.ai", "openrouter-provider", "https://www.cerebras.ai/"),
    ("Certuma", "certuma.ai", "forbes-ai-50-brink-2026", "https://www.certuma.ai/"),
    ("Chai Discovery", "chaidiscovery.com", "forbes-ai-50-2026", "https://www.chaidiscovery.com/"),
    ("ChipAgents", "chipagents.ai", "cb-insights-ai-100-2026", "https://chipagents.ai/"),
    ("Clarifai", "clarifai.com", "openrouter-provider", "https://clarifai.com/"),
    ("Clay", "clay.com", "forbes-ai-50-2026", "https://www.clay.com/"),
    ("Cloudflare", "cloudflare.com", "openrouter-provider", "https://www.cloudflare.com/"),
    ("Cognition", "cognition.com", "forbes-ai-50-2026", "https://cognition.com/"),
    ("Cohere", "cohere.com", "forbes-ai-50-2026", "https://cohere.com/"),
    ("CoreWeave", "coreweave.com", "openrouter-provider", "https://www.coreweave.com/"),
    ("Creatify AI", "creatify.ai", "cb-insights-ai-100-2026", "https://creatify.ai/"),
    ("Crusoe", "crusoe.ai", "forbes-ai-50-2026", "https://www.crusoe.ai/"),
    ("Cursor", "cursor.com", "forbes-ai-50-2026", "https://cursor.com/"),
    ("CuspAI", "cusp.ai", "cb-insights-ai-100-2026", "https://cusp.ai/"),
    ("Cyera", "cyera.com", "forbes-ai-50-2026", "https://www.cyera.com/"),
    ("Dash0", "dash0.com", "cb-insights-ai-100-2026", "https://www.dash0.com/"),
    ("Databricks", "databricks.com", "forbes-ai-50-2026", "https://www.databricks.com/"),
    ("Decagon", "decagon.ai", "forbes-ai-50-2026", "https://decagon.ai/"),
    ("Decart", "decart.ai", "openrouter-provider", "https://decart.ai/"),
    ("Deepgram", "deepgram.com", "openrouter-provider", "https://deepgram.com/"),
    ("DeepInfra", "deepinfra.com", "openrouter-provider", "https://deepinfra.com/"),
    ("DeepJudge", "deepjudge.ai", "cb-insights-ai-100-2026", "https://www.deepjudge.ai/"),
    ("DeepSeek", "deepseek.com", "arena-org", "https://www.deepseek.com/"),
    ("depthfirst", "depthfirst.com", "cb-insights-ai-100-2026", "https://depthfirst.com/"),
    ("DigitalOcean", "digitalocean.com", "openrouter-provider", "https://www.digitalocean.com/"),
    ("E2B", "e2b.dev", "cb-insights-ai-100-2026", "https://e2b.dev/"),
    ("ElevenLabs", "elevenlabs.io", "forbes-ai-50-2026", "https://elevenlabs.io/"),
    ("Elicit", "elicit.com", "cb-insights-ai-100-2026", "https://elicit.com/"),
    ("EliseAI", "eliseai.com", "forbes-ai-50-2026", "https://eliseai.com/"),
    ("Ellipsis Health", "ellipsishealth.com", "cb-insights-ai-100-2026", "https://ellipsishealth.com/"),
    ("Etched", "etched.com", "hugging-face-org", "https://www.etched.com/"),
    ("Fal", "fal.ai", "forbes-ai-50-2026", "https://fal.ai/"),
    ("FieldAI", "fieldai.com", "cb-insights-ai-100-2026", "https://www.fieldai.com/"),
    ("Fireworks AI", "fireworks.ai", "forbes-ai-50-2026", "https://fireworks.ai/"),
    ("Flapping Airplanes", "flappingairplanes.com", "forbes-ai-50-brink-2026", "https://flappingairplanes.com/"),
    ("FriendliAI", "friendli.ai", "cb-insights-ai-100-2026", "https://friendli.ai/"),
    ("Further AI", "furtherai.com", "cb-insights-ai-100-2026", "https://www.furtherai.com/"),
    ("Gamma", "gamma.app", "forbes-ai-50-2026", "https://gamma.app/"),
    ("Generalist AI", "generalistai.com", "cb-insights-ai-100-2026", "https://generalistai.com/"),
    ("Genmo", "genmo.ai", "hugging-face-org", "https://www.genmo.ai/"),
    ("Genspark.ai", "genspark.ai", "forbes-ai-50-2026", "https://www.genspark.ai/"),
    ("Geordie AI", "geordie.ai", "cb-insights-ai-100-2026", "https://www.geordie.ai/"),
    ("Giga", "giga.ai", "forbes-ai-50-brink-2026", "https://giga.ai/"),
    ("Glean", "glean.com", "forbes-ai-50-2026", "https://www.glean.com/"),
    ("Google", "google.com", "arena-org", "https://ai.google/"),
    ("Gravis Robotics", "gravisrobotics.com", "cb-insights-ai-100-2026", "https://www.gravisrobotics.com/"),
    ("Groq", "groq.com", "openrouter-provider", "https://groq.com/"),
    ("Harvey", "harvey.ai", "forbes-ai-50-2026", "https://www.harvey.ai/"),
    ("HeyGen", "heygen.com", "forbes-ai-50-2026", "https://www.heygen.com/"),
    ("Hugging Face", "huggingface.co", "hugging-face-org", "https://huggingface.co/"),
    ("Humans&", "humansand.ai", "forbes-ai-50-brink-2026", "https://humansand.ai/"),
    ("IBM", "ibm.com", "arena-org", "https://www.ibm.com/solutions/artificial-intelligence"),
    ("Inception", "inceptionlabs.ai", "openrouter-provider", "https://www.inceptionlabs.ai/"),
    ("InCountry", "incountry.com", "cb-insights-ai-100-2026", "https://incountry.com/"),
    ("Inflection", "inflection.ai", "openrouter-provider", "https://inflection.ai/"),
    ("InOrbit", "inorbit.ai", "cb-insights-ai-100-2026", "https://www.inorbit.ai/"),
    ("Irregular", "irregular.com", "forbes-ai-50-brink-2026", "https://irregular.com/"),
    ("Keycard", "keycard.ai", "cb-insights-ai-100-2026", "https://www.keycard.ai/"),
    ("Knostic", "knostic.ai", "cb-insights-ai-100-2026", "https://www.knostic.ai/"),
    ("Krea", "krea.ai", "forbes-ai-50-2026", "https://www.krea.ai/"),
    ("LanceDB", "lancedb.com", "cb-insights-ai-100-2026", "https://www.lancedb.com/"),
    ("Latent Health", "latenthealth.com", "forbes-ai-50-brink-2026", "https://latenthealth.com/"),
    ("Layer Health", "layerhealth.com", "cb-insights-ai-100-2026", "https://www.layerhealth.com/"),
    ("Legora", "legora.com", "forbes-ai-50-2026", "https://legora.com/"),
    ("Leo AI", "getleo.ai", "cb-insights-ai-100-2026", "https://www.getleo.ai/"),
    ("Linkup", "linkup.so", "cb-insights-ai-100-2026", "https://www.linkup.so/"),
    ("Liquid AI", "liquid.ai", "openrouter-provider", "https://www.liquid.ai/"),
    ("Listen Labs", "listenlabs.ai", "forbes-ai-50-2026", "https://listenlabs.ai/"),
    ("LlamaIndex", "llamaindex.ai", "cb-insights-ai-100-2026", "https://www.llamaindex.ai/"),
    ("LMArena", "arena.ai", "cb-insights-ai-100-2026", "https://arena.ai/"),
    ("Lovable", "lovable.dev", "forbes-ai-50-2026", "https://lovable.dev/"),
    ("LTX", "ltx.io", "hugging-face-org", "https://ltx.io/"),
    ("Lumana", "lumana.ai", "cb-insights-ai-100-2026", "https://www.lumana.ai/"),
    ("Lyzr", "lyzr.ai", "cb-insights-ai-100-2026", "https://www.lyzr.ai/"),
    ("Maisa AI", "maisa.ai", "cb-insights-ai-100-2026", "https://maisa.ai/"),
    ("Mercor", "mercor.com", "forbes-ai-50-2026", "https://www.mercor.com/"),
    ("Meta", "meta.com", "arena-org", "https://ai.meta.com/"),
    ("Micro1", "micro1.ai", "forbes-ai-50-brink-2026", "https://www.micro1.ai/"),
    ("Microsoft", "microsoft.com", "openrouter-provider", "https://www.microsoft.com/en-us/ai"),
    ("Midjourney", "midjourney.com", "forbes-ai-50-2026", "https://www.midjourney.com/"),
    ("MiniMax", "minimax.io", "arena-org", "https://www.minimax.io/"),
    ("Mistral AI", "mistral.ai", "forbes-ai-50-2026", "https://mistral.ai/"),
    ("Modal", "modal.com", "openrouter-provider", "https://modal.com/"),
    ("Moonlake AI", "moonlakeai.com", "cb-insights-ai-100-2026", "https://moonlakeai.com/"),
    ("Moonshot AI", "moonshot.cn", "arena-org", "https://www.moonshot.cn/"),
    ("Moonvalley", "moonvalley.com", "cb-insights-ai-100-2026", "https://www.moonvalley.com/"),
    ("Narada", "narada.ai", "cb-insights-ai-100-2026", "https://narada.ai/"),
    ("Nebius", "nebius.com", "openrouter-provider", "https://nebius.com/"),
    ("Nectar Social", "nectarsocial.com", "forbes-ai-50-brink-2026", "https://www.nectarsocial.com/"),
    ("Netic", "netic.ai", "cb-insights-ai-100-2026", "https://www.netic.ai/"),
    ("Newton Research", "newtonresearch.ai", "cb-insights-ai-100-2026", "https://www.newtonresearch.ai/"),
    ("Notion", "notion.com", "forbes-ai-50-2026", "https://www.notion.com/"),
    ("Nous Research", "nousresearch.com", "hugging-face-org", "https://nousresearch.com/"),
    ("Novita", "novita.ai", "openrouter-provider", "https://novita.ai/"),
    ("NVIDIA", "nvidia.com", "arena-org", "https://www.nvidia.com/en-us/"),
    ("Oboe", "oboe.com", "cb-insights-ai-100-2026", "https://oboe.com/"),
    ("OpenAI", "openai.com", "forbes-ai-50-2026", "https://openai.com/"),
    ("OpenEvidence", "openevidence.com", "forbes-ai-50-2026", "https://www.openevidence.com/"),
    ("OpenRouter", "openrouter.ai", "forbes-ai-50-brink-2026", "https://openrouter.ai/"),
    ("Paid", "paid.ai", "cb-insights-ai-100-2026", "https://paid.ai/"),
    ("Parallel", "parallel.ai", "cb-insights-ai-100-2026", "https://parallel.ai/"),
    ("Perceptron", "perceptron.inc", "openrouter-provider", "https://www.perceptron.inc/"),
    ("Periodic Labs", "periodic.com", "forbes-ai-50-brink-2026", "https://periodic.com/"),
    ("Perplexity", "perplexity.ai", "forbes-ai-50-2026", "https://www.perplexity.ai/"),
    ("Persona AI", "persona.ai", "cb-insights-ai-100-2026", "https://persona.ai/"),
    ("Physical Intelligence", "pi.website", "forbes-ai-50-2026", "https://www.pi.website/"),
    ("PlayerZero", "playerzero.ai", "cb-insights-ai-100-2026", "https://playerzero.ai/"),
    ("Poolside", "poolside.ai", "openrouter-provider", "https://poolside.ai/"),
    ("Positron", "positron.ai", "cb-insights-ai-100-2026", "https://www.positron.ai/"),
    ("Procure Ai", "procure.ai", "cb-insights-ai-100-2026", "https://www.procure.ai/"),
    ("Profound", "tryprofound.com", "cb-insights-ai-100-2026", "https://www.tryprofound.com/"),
    ("Prophet", "prophetsecurity.ai", "cb-insights-ai-100-2026", "https://www.prophetsecurity.ai/"),
    ("Qbiq", "qbiq.ai", "cb-insights-ai-100-2026", "https://www.qbiq.ai/"),
    ("Questflow", "questflow.ai", "cb-insights-ai-100-2026", "https://questflow.ai/"),
    ("Raspberry AI", "raspberry.ai", "cb-insights-ai-100-2026", "https://www.raspberry.ai/"),
    ("Recraft", "recraft.ai", "openrouter-provider", "https://www.recraft.ai/"),
    ("Reevo", "reevo.ai", "cb-insights-ai-100-2026", "https://reevo.ai/"),
    ("Reflection", "reflection.ai", "forbes-ai-50-2026", "https://reflection.ai/"),
    ("Reka", "reka.ai", "arena-org", "https://reka.ai/"),
    ("Replit", "replit.com", "forbes-ai-50-2026", "https://replit.com/"),
    ("Resolve AI", "resolve.ai", "forbes-ai-50-brink-2026", "https://resolve.ai/"),
    ("Rhino Federated Computing", "rhinofcp.com", "cb-insights-ai-100-2026", "https://www.rhinofcp.com/"),
    ("Ricursive Intelligence", "ricursive.com", "forbes-ai-50-brink-2026", "https://www.ricursive.com/"),
    ("Rogo", "rogo.com", "forbes-ai-50-2026", "https://rogo.com/"),
    ("Rox", "rox.com", "forbes-ai-50-brink-2026", "https://www.rox.com/"),
    ("Runway", "runway.com", "forbes-ai-50-2026", "https://runway.com/"),
    ("Safe Superintelligence", "ssi.inc", "forbes-ai-50-2026", "https://ssi.inc/"),
    ("Sakana AI", "sakana.ai", "openrouter-provider", "https://sakana.ai/"),
    ("Salient", "trysalient.com", "cb-insights-ai-100-2026", "https://www.trysalient.com/"),
    ("SambaNova", "sambanova.ai", "forbes-ai-50-2026", "https://sambanova.ai/"),
    ("Seekr", "seekr.com", "cb-insights-ai-100-2026", "https://www.seekr.com/"),
    ("Serval", "serval.com", "cb-insights-ai-100-2026", "https://www.serval.com/"),
    ("Sierra", "sierra.ai", "forbes-ai-50-2026", "https://sierra.ai/"),
    ("Simbian", "simbian.ai", "cb-insights-ai-100-2026", "https://simbian.ai/"),
    ("Simile", "simile.com", "forbes-ai-50-brink-2026", "https://www.simile.com/"),
    ("SiPearl", "sipearl.com", "cb-insights-ai-100-2026", "https://sipearl.com/"),
    ("Skild AI", "skild.ai", "forbes-ai-50-2026", "https://www.skild.ai/"),
    ("Speak", "speak.com", "forbes-ai-50-2026", "https://www.speak.com/"),
    ("Stability AI", "stability.ai", "hugging-face-org", "https://stability.ai/"),
    ("StackOne", "stackone.com", "cb-insights-ai-100-2026", "https://www.stackone.com/"),
    ("StepFun", "stepfun.com", "arena-org", "https://www.stepfun.com/"),
    ("Straiker", "straiker.ai", "cb-insights-ai-100-2026", "https://www.straiker.ai/"),
    ("Strella", "strella.io", "cb-insights-ai-100-2026", "https://www.strella.io/"),
    ("Suno", "suno.com", "forbes-ai-50-2026", "https://suno.com/"),
    ("Superblocks", "superblocks.com", "cb-insights-ai-100-2026", "https://www.superblocks.com/"),
    ("Surge AI", "surgehq.ai", "forbes-ai-50-2026", "https://surgehq.ai/"),
    ("Synthesia", "synthesia.io", "forbes-ai-50-2026", "https://www.synthesia.io/"),
    ("Tencent", "tencent.com", "arena-org", "https://www.tencent.com/"),
    ("Tenstorrent", "tenstorrent.com", "openrouter-provider", "https://tenstorrent.com/"),
    ("The Bot Company", "bot.co", "cb-insights-ai-100-2026", "https://www.bot.co/"),
    ("Thinking Machines Lab", "thinkingmachines.ai", "forbes-ai-50-2026", "https://thinkingmachines.ai/"),
    ("Together AI", "together.ai", "forbes-ai-50-2026", "https://www.together.ai/"),
    ("TollBit", "tollbit.com", "forbes-ai-50-brink-2026", "https://tollbit.com/"),
    ("Unsloth AI", "unsloth.ai", "hugging-face-org", "https://unsloth.ai/"),
    ("Upstage", "upstage.ai", "openrouter-provider", "https://www.upstage.ai/"),
    ("Venice", "venice.ai", "openrouter-provider", "https://venice.ai/"),
    ("Virtue AI", "virtueai.com", "cb-insights-ai-100-2026", "https://www.virtueai.com/"),
    ("Wan-AI", "wan.video", "hugging-face-org", "https://wan.video/"),
    ("Wispr Flow", "wisprflow.ai", "forbes-ai-50-brink-2026", "https://wisprflow.ai/"),
    ("Worktrace AI", "worktrace.ai", "forbes-ai-50-brink-2026", "https://www.worktrace.ai/"),
    ("World Labs", "worldlabs.ai", "forbes-ai-50-2026", "https://www.worldlabs.ai/"),
    ("xAI", "x.ai", "arena-org", "https://x.ai/"),
    ("Xiaomi", "mi.com", "arena-org", "https://www.mi.com/us/"),
    ("Z.AI", "z.ai", "arena-org", "https://chat.z.ai/"),
]
