ENTRIES = []

def add(**kw):
    ENTRIES.append(kw)

add(
    id="hipaa",
    name="HIPAA",
    short="HIPAA",
    family="HIPAA",
    kind="regulation",
    geography=["US"],
    industry=["healthcare"],
    issuer="U.S. Department of Health and Human Services, Office for Civil Rights",
    eli5="A U.S. law about health information. There is no official HIPAA certificate. A company can sign a contract and say it follows the rules. That is not the same as a third-party audit.",
    elaborate="The Health Insurance Portability and Accountability Act of 1996, as amended (including HITECH), is U.S. federal law. The Privacy Rule, Security Rule, and Breach Notification Rule are administered by HHS OCR. Covered entities and business associates must comply. There is no HHS-issued 'HIPAA certification.' OCR does not license vendors. A Business Associate Agreement (BAA) is a contract, not an audit. Self-attestation, a security white paper, or a SOC 2 with a HIPAA mapping is not a government approval. HITRUST r2 is often used as a private-sector proxy because the CSF maps HIPAA; it is still not an OCR certificate. 'SOC 2 + HIPAA' is not a separate AICPA product. A buyer should obtain a BAA if required, read whether the vendor will sign one for the product in scope, and treat any third-party report as supporting evidence only. Typical evidence is the BAA plus, if offered, a SOC 2, HITRUST letter, or independent assessment that actually tested Security Rule controls. A trust-page badge that says 'HIPAA compliant' with no BAA and no report is a claim. HIPAA does not apply to all health-adjacent data, and it is not a privacy law for ordinary consumer apps.",
    lat=38.9072,
    lng=-77.0369,
    related=["hitrust-r2", "hitrust-csf", "hds"],
    weight=3,
)

add(
    id="hitrust-csf",
    name="HITRUST CSF",
    short="HITRUST CSF",
    family="HITRUST",
    kind="framework",
    geography=["US", "global"],
    industry=["healthcare", "all"],
    issuer="HITRUST Alliance",
    eli5="A big control library that mixes many laws and standards into one set. By itself it is a book of controls, not a certificate. The certificates are e1, i1, and r2.",
    elaborate="The HITRUST CSF (also called the HITRUST Framework) is a proprietary control framework maintained by HITRUST Alliance. It maps and tailors requirements from HIPAA, NIST, ISO, PCI, and many other sources into a single catalog. Organizations use it to scope assessments. Holding 'the CSF' is not a certification. The certifiable assessment products built on the CSF are e1, i1, and r2 (and, separately, some targeted or AI-related HITRUST assessments). A vendor that says 'HITRUST CSF certified' without naming e1, i1, or r2 is being vague; ask which assessment and ask for the HITRUST-issued letter. The CSF is threat-adaptive; requirement sets change as HITRUST updates mappings. It is not a government framework, not NIST CSF, and not ISO 27001, though it maps to them. Typical evidence for the framework itself is none — you want the certification letter. This entry exists so a register can distinguish the library from the certificates. Score the letter, not the acronym.",
    lat=33.1507,
    lng=-96.8236,
    related=["hitrust-e1", "hitrust-i1", "hitrust-r2", "hipaa", "nist-csf"],
    weight=4,
)

add(
    id="hitrust-e1",
    name="HITRUST e1",
    short="HITRUST e1",
    family="HITRUST",
    kind="certification",
    geography=["US", "global"],
    industry=["healthcare", "all"],
    issuer="HITRUST Alliance",
    eli5="The smallest HITRUST certificate. An assessor checks a short list of basic security hygiene controls. It lasts one year. It is not the same as the large r2 report hospitals often want.",
    elaborate="HITRUST e1 (Essentials, 1-year) is a validated assessment and certification against a fixed set of foundational CSF controls — HITRUST documents this as 43 core controls. A HITRUST Authorized External Assessor performs the validated assessment; HITRUST quality-reviews the file and issues the certification. Validity is one year. e1 is entry-level assurance for lower-risk or less complex organizations. It is not r2, not a HIPAA certificate, and not equivalent to a SOC 2 Type II covering a broad system. Work on e1 can later be reused toward i1. Buyers should read the HITRUST certification letter for the assessed entity, scope, and expiration, and should not accept 'we are HITRUST' without the level. Typical evidence is the HITRUST-issued certification letter, sometimes shared through HITRUST Assessment XChange. A self-assessment against e1 controls without HITRUST certification is not e1. Score e1 below i1 and well below r2.",
    lat=33.1507,
    lng=-96.8236,
    related=["hitrust-i1", "hitrust-r2", "hitrust-csf"],
    weight=5,
)

add(
    id="hitrust-i1",
    name="HITRUST i1",
    short="HITRUST i1",
    family="HITRUST",
    kind="certification",
    geography=["US", "global"],
    industry=["healthcare", "all"],
    issuer="HITRUST Alliance",
    eli5="A one-year HITRUST certificate on a larger, fixed set of security practices. Stronger than e1. Not as tailored or deep as r2. Issued by HITRUST after an assessor’s work.",
    elaborate="HITRUST i1 (Implemented, 1-year) is a validated assessment against a fixed, threat-adaptive set of CSF controls — HITRUST documents this as 182 controls focused on implemented leading practices. A HITRUST Authorized External Assessor performs the work; HITRUST issues the certification after quality assurance. Validity is one year. i1 is moderate assurance. It is more comprehensive than e1 and less tailored than r2. r2 remains the assessment most large U.S. healthcare delivery organizations still ask for when they want a risk-based, multi-authoritative-source report. i1 is not a government authorization and not a SOC 2. HITRUST describes i1 as a certification with a defined control set and centralized QA, which is a different product shape from a CPA's SOC 2 opinion. Buyers should read the letter, the scope, and whether any optional authoritative sources were added. Typical evidence is the HITRUST certification letter. Work from i1 can be applied toward r2. Do not treat i1 and r2 as interchangeable on a hospital security questionnaire.",
    lat=33.1507,
    lng=-96.8236,
    related=["hitrust-e1", "hitrust-r2", "hitrust-csf", "soc-2-type-ii"],
    weight=7,
)

add(
    id="hitrust-r2",
    name="HITRUST r2",
    short="HITRUST r2",
    family="HITRUST",
    kind="certification",
    geography=["US", "global"],
    industry=["healthcare", "all"],
    issuer="HITRUST Alliance",
    eli5="The large HITRUST certificate. Controls are picked from the library based on risk and which laws apply. It lasts two years, with a check in the middle. This is the one most hospitals mean.",
    elaborate="HITRUST r2 (Risk-based, 2-year) is the highest HITRUST validated assessment commonly seen on U.S. healthcare vendor pages. The requirement set is tailored from the CSF using risk factors such as data volumes, systems, and selected authoritative sources (HIPAA, NIST CSF, and others as scoped). A HITRUST Authorized External Assessor performs the validated assessment; HITRUST issues the certification after quality review. The certification is valid for two years, with a required interim assessment. Domain scoring thresholds apply; r2 is not a participation trophy. It is still not an HHS or OCR certificate. It does not replace a BAA. It does not prove that a specific product module added last month was in the assessed scope. Buyers should read the certification letter, the scope, included authoritative sources, and whether the interim is current. Typical evidence is the HITRUST letter and, under NDA, the full assessment report. r2 is often accepted in place of a stack of smaller questionnaires; that is a buyer policy choice, not a law. e1 and i1 are different products.",
    lat=33.1507,
    lng=-96.8236,
    related=["hitrust-e1", "hitrust-i1", "hitrust-csf", "hipaa", "nist-csf"],
    weight=10,
)

add(
    id="fedramp",
    name="FedRAMP",
    short="FedRAMP",
    family="FedRAMP",
    kind="authorization",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="U.S. General Services Administration, FedRAMP Program Management Office",
    eli5="A U.S. government program that checks cloud services before agencies use them. Look the service up on the FedRAMP Marketplace. A blog badge is not an authorization.",
    elaborate="The Federal Risk and Authorization Management Program is the U.S. government path for authorizing cloud services that process federal data. Historically, offerings were authorized at FIPS 199 impact levels Low, Moderate, or High, based on NIST SP 800-53 baselines (Rev. 5 is the current baseline family). An independent assessor (3PAO) produces a security assessment package; an agency authorizes use (ATO), and the offering is listed on the FedRAMP Marketplace. The PMO does not 'certify' a company; it lists a cloud service offering. FedRAMP Tailored LI-SaaS is a reduced path for low-impact SaaS and is a separate entry here. In 2026 the program published Consolidated Rules (CR26) that introduce Certification Classes A–D and 'FedRAMP Certified' language; marketplace listings and agency ATOs at Low/Moderate/High remain the labels most buyers still verify. This register does not treat consultant class-mapping blogs as the source of truth — verify the live Marketplace status. FedRAMP is not SOC 2. It is not DoD SRG Impact Level 4/5/6, though packages are reused. Typical evidence is the Marketplace listing for the exact offering name, plus a package under government NDA. 'FedRAMP in process' is not authorized. Weight is high because a real authorization is hard to fake and costly to maintain.",
    lat=38.8951,
    lng=-77.0364,
    related=["fedramp-li-saas", "govramp", "tx-ramp", "nist-800-53"],
    weight=12,
    note="kind uses 'authorization' because that is what agencies and the Marketplace still call a package; CR26 also uses 'certification.' Not a CPA attestation.",
)

add(
    id="fedramp-li-saas",
    name="FedRAMP Tailored LI-SaaS",
    short="FedRAMP LI-SaaS",
    family="FedRAMP",
    kind="authorization",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="U.S. General Services Administration, FedRAMP Program Management Office",
    eli5="A lighter FedRAMP path for simple, low-impact software in the cloud. It is real. It is not the same as a Moderate or High authorization.",
    elaborate="FedRAMP Tailored, Low-Impact Software-as-a-Service (LI-SaaS), is a real FedRAMP policy path for low-risk SaaS where a full Low baseline is disproportionate. The Tailored policy identifies which Low-baseline requirements typically remain on the provider versus the customer or underlying platform, and it uses FedRAMP templates. Authorization is an Agency ATO; there was no JAB P-ATO path for LI-SaaS. The offering should still appear on the FedRAMP Marketplace with the tailored/LI-SaaS designation. It is not Moderate. It is not High. It is not a substitute for DoD IL4. Under CR26, public commentary maps former Low and LI-SaaS toward Certification Class B; buyers should still read the Marketplace line, not a class nickname on a slide. Typical evidence is the Marketplace listing for that offering. A vendor that says 'FedRAMP Tailored' without a listing is making a claim. This entry exists because the user-facing name is common and is not a hybrid invention.",
    lat=38.8951,
    lng=-77.0364,
    related=["fedramp", "govramp", "nist-800-53"],
    weight=8,
)

add(
    id="govramp",
    name="GovRAMP",
    short="GovRAMP",
    family="RAMP",
    kind="authorization",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="GovRAMP (StateRAMP Inc., d/b/a GovRAMP)",
    eli5="A shared cloud-security program for U.S. state and local government, built on NIST 800-53. It used to be called StateRAMP. Check the authorized-products list, not a sticker.",
    elaborate="GovRAMP is the current name of the multi-state cloud authorization program that operated as StateRAMP. The rebrand was announced 14 February 2025. StateRAMP Inc. remains the legal entity and operates as GovRAMP; existing memberships and authorizations continued. The program uses NIST SP 800-53-based security status (Ready, Authorized, and program statuses such as Core — verify current status names on govramp.org). It is voluntary at the program level; individual states choose whether and how to require it. It is not FedRAMP. FedRAMP does not automatically grant GovRAMP, or the reverse, though reciprocity conversations exist and Texas TX-RAMP has its own reciprocity rules. Buyers at state agencies should look up the product on the GovRAMP authorized list and confirm the status and impact level. Typical evidence is the public product listing. Older contracts and trust pages will still say StateRAMP; treat that as the same program unless the listing is gone. This is not a CPA attestation.",
    lat=38.9072,
    lng=-77.0369,
    related=["stateramp", "tx-ramp", "fedramp", "nist-800-53"],
    weight=10,
)

add(
    id="stateramp",
    name="StateRAMP",
    short="StateRAMP",
    family="RAMP",
    kind="authorization",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="StateRAMP Inc. (now d/b/a GovRAMP)",
    eli5="The old name for GovRAMP. Same organization. If a page still says StateRAMP Authorized, look it up on the GovRAMP list to see if that status is still live.",
    elaborate="StateRAMP was the name of the state and local cloud authorization program operated by StateRAMP Inc. On 14 February 2025 the program began operating as GovRAMP. The legal entity did not dissolve. Authorizations were not wiped. Many state documents, older AOCs, and vendor trust pages still use StateRAMP. Texas DIR materials for TX-RAMP reciprocity still mention StateRAMP in places and, in the TX-RAMP Program Manual 4.0, say that GovRAMP includes StateRAMP. This entry is the historical name, not a second program. Do not score StateRAMP and GovRAMP as two authorizations for one listing. Verify the live product status on the GovRAMP authorized list. Typical evidence is that listing, or an older StateRAMP letter that still matches a current listing. Weight is lower than GovRAMP so a double-count does not inflate a score if both strings appear on a page.",
    lat=38.9072,
    lng=-77.0369,
    related=["govramp", "tx-ramp", "fedramp"],
    weight=4,
    note="Renamed to GovRAMP in February 2025; not a distinct live program.",
)

add(
    id="tx-ramp",
    name="TX-RAMP",
    short="TX-RAMP",
    family="RAMP",
    kind="authorization",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="Texas Department of Information Resources",
    eli5="Texas's own cloud-security authorization for vendors that sell to Texas state agencies. Required by Texas law for in-scope cloud services. FedRAMP does not list you automatically.",
    elaborate="The Texas Risk and Authorization Management Program is established under Texas Government Code §2054.0593 and run by the Texas Department of Information Resources (DIR). Cloud computing services in scope must be certified to contract with Texas state agencies. DIR publishes Level 1 and Level 2 certification. FedRAMP and GovRAMP/StateRAMP can support reciprocity, but as of 30 October 2024 DIR no longer auto-lists those products; the vendor must file a TX-RAMP request (SPECTRIM) and wait for DIR validation. FedRAMP Low has been treated as corresponding to Level 1; Moderate or High to Level 2 — confirm in the current TX-RAMP manual, not in a blog. TX-RAMP is not FedRAMP and not a SOC 2. Typical evidence is the product's presence on the DIR TX-RAMP certified list at the required level. A FedRAMP Marketplace URL alone is not TX-RAMP. Provisional statuses exist; read the list. This is one of the few U.S. state cloud authorizations with a statutory mandate, which is why it is a separate entry from GovRAMP.",
    lat=30.2672,
    lng=-97.7431,
    related=["fedramp", "govramp", "stateramp"],
    weight=9,
)

add(
    id="cmmc-l1",
    name="CMMC Level 1",
    short="CMMC L1",
    family="CMMC",
    kind="certification",
    geography=["US"],
    industry=["public-sector"],
    issuer="U.S. Department of Defense; status posted in SPRS",
    eli5="The basic Cybersecurity Maturity Model Certification level for contractors that handle ordinary federal contract information. Today it is a self-assessment, posted in a government system.",
    elaborate="CMMC Level 1 (Self) is defined in 32 CFR Part 170. It requires the 15 basic safeguarding requirements in FAR 52.204-21 for Federal Contract Information (FCI). The organization seeking assessment performs an annual self-assessment and posts results in the Supplier Performance Risk System (SPRS), with an affirmation. Plans of action and milestones are not permitted at Level 1. This is not a C3PAO certificate. It is not protection of CUI (that is Level 2). It is not NIST SP 800-171. Phase 1 of CMMC implementation, in effect since November 2025, includes Level 1 self-assessment as a condition of award where designated. Typical evidence is an SPRS status the prime or the Department can see — not a PDF badge on a marketing site. A public 'CMMC L1 certified' claim without SPRS is unverifiable. Do not confuse this with Cyber Essentials or CIS IG1.",
    lat=38.8719,
    lng=-77.0563,
    related=["cmmc-l2", "nist-800-171"],
    weight=6,
)

add(
    id="cmmc-l2",
    name="CMMC Level 2",
    short="CMMC L2",
    family="CMMC",
    kind="certification",
    geography=["US"],
    industry=["public-sector"],
    issuer="U.S. Department of Defense / The Cyber AB (for C3PAO assessments)",
    eli5="The CMMC level for contractors that handle controlled unclassified information. It maps to NIST 800-171. A third-party certificate exists, but as of July 2026 the Department paused requiring those third-party assessments.",
    elaborate="CMMC Level 2 is the CUI level. The security requirement set is the 110 requirements of NIST SP 800-171 Revision 2, as required by DFARS 252.204-7012. Two statuses exist in the rule: Level 2 (Self), a self-assessment posted to SPRS every three years with annual affirmation, and Level 2 (C3PAO), a third-party assessment by a Cyber AB-accredited C3PAO. On 13 July 2026 the Department of War announced immediate suspension of CMMC Phase II, which would have made C3PAO Level 2 a routine condition of award, and paused later phases. Phase I self-assessment requirements remain in place. Existing C3PAO certificates were not voided. Level 3 (DIBCAC, NIST SP 800-172) is out of scope for this entry and is also paused for new mandates. CMMC is not FedRAMP. Typical evidence for a C3PAO certificate is the Cyber AB / CMMC marketplace listing and SPRS status. Typical evidence for self is SPRS. A logo is not enough. DFARS 252.204-7012 safeguarding and incident reporting remain regardless of the Phase II pause.",
    lat=38.8719,
    lng=-77.0563,
    related=["cmmc-l1", "nist-800-171", "nist-800-53", "fedramp"],
    weight=11,
)

add(
    id="nist-800-53",
    name="NIST SP 800-53",
    short="NIST 800-53",
    family="NIST",
    kind="framework",
    geography=["US"],
    industry=["public-sector", "cloud"],
    issuer="National Institute of Standards and Technology",
    eli5="A large U.S. government catalog of security and privacy controls. Agencies and FedRAMP use it. A company cannot be '800-53 certified.' It can be assessed against a baseline.",
    elaborate="NIST Special Publication 800-53 is the Security and Privacy Controls for Information Systems and Organizations catalog. Revision 5 is the current revision used with FedRAMP baselines. It is a control catalog, not a certification program. There is no NIST-issued 800-53 certificate. FedRAMP, GovRAMP, TX-RAMP, and many agency authorizations select baselines (Low/Moderate/High, or program-specific) from this catalog. A vendor claim of 'NIST 800-53 compliant' without a baseline, an assessor, and a package is a self-assertion. Buyers should ask which revision, which baseline, who assessed it, and whether the result is a FedRAMP package, a GovRAMP status, or an internal mapping. Typical evidence is the authorization listing or an assessment report, not the SP itself. 800-53 is not 800-171. 800-171 is a derived set for nonfederal systems that process CUI. Do not score a 800-53 poster as equal to FedRAMP.",
    lat=39.1403,
    lng=-77.2200,
    related=["fedramp", "nist-800-171", "nist-csf", "govramp"],
    weight=4,
)

add(
    id="nist-800-171",
    name="NIST SP 800-171",
    short="NIST 800-171",
    family="NIST",
    kind="framework",
    geography=["US"],
    industry=["public-sector"],
    issuer="National Institute of Standards and Technology",
    eli5="The NIST control set for protecting controlled unclassified information on a contractor's own systems. Defense contracts have pointed at Revision 2. It is not a certificate by itself.",
    elaborate="NIST SP 800-171, Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations, specifies security requirements for CUI on contractor systems. Revision 2 is the version CMMC Level 2 and DFARS 252.204-7012 currently use. Revision 3 has been published; do not assume a contract moved to Rev. 3 unless the contract says so. There is no NIST 800-171 certificate. Contractors self-assess and post scores to SPRS; some obtain a CMMC Level 2 C3PAO assessment against the same 110 requirements. A '800-171 compliant' badge on a trust page is a claim. Typical evidence is the SPRS score date, a system security plan, and, if offered, a CMMC status. 800-171 is not 800-53 and not FedRAMP. It does not apply merely because a SaaS vendor sells to a company that has a defense contract — it applies when CUI is processed on the vendor's system and the flow-down says so.",
    lat=39.1403,
    lng=-77.2200,
    related=["cmmc-l2", "nist-800-53", "cmmc-l1"],
    weight=5,
)

add(
    id="nist-csf",
    name="NIST Cybersecurity Framework",
    short="NIST CSF",
    family="NIST",
    kind="framework",
    geography=["US", "global"],
    industry=["all"],
    issuer="National Institute of Standards and Technology",
    eli5="A popular way to organize cybersecurity work: identify, protect, detect, respond, recover — and now govern. Anyone can say they use it. NIST does not hand out CSF certificates.",
    elaborate="The NIST Cybersecurity Framework is voluntary guidance. CSF 2.0 was published in February 2024 and adds a Govern function to Identify, Protect, Detect, Respond, and Recover. Organizations adopt it as a language for programs and assessments. NIST does not certify companies to the CSF. HITRUST can produce a NIST CSF scorecard from a HITRUST assessment; that is a HITRUST product, not a NIST certificate. A SOC 2 or ISO 27001 can be mapped to CSF functions; the mapping is not a CSF certification. Buyers should treat 'aligned to NIST CSF' as a narrative unless an independent report maps controls to the Core. Typical evidence is that mapping or a HITRUST CSF scorecard, not a NIST seal. This framework is widely claimed and weakly evidentiary, so it scores low as a public-disclosure mover.",
    lat=39.1403,
    lng=-77.2200,
    related=["nist-800-53", "nist-ai-rmf", "hitrust-r2", "cis-controls"],
    weight=3,
)

add(
    id="nist-ai-rmf",
    name="NIST AI Risk Management Framework",
    short="NIST AI RMF",
    family="NIST",
    kind="framework",
    geography=["US", "global"],
    industry=["ai"],
    issuer="National Institute of Standards and Technology",
    eli5="A NIST guidebook for managing risks of AI systems. Companies can follow it. NIST does not certify that they did. It is not the EU AI Act.",
    elaborate="The NIST AI Risk Management Framework (AI RMF 1.0, NIST AI 100-1, January 2023) is voluntary guidance for governing, mapping, measuring, and managing risks of AI systems. A companion playbook exists. NIST does not issue AI RMF certificates. A vendor claim of 'NIST AI RMF aligned' is a self-description unless an independent assessor mapped practices to the Core and documented evidence. It is not ISO/IEC 42001, which is a certifiable AIMS. It is not the EU AI Act. Buyers who need AI assurance should prefer a scoped ISO 42001 certificate, a system card with evaluation results, and contractual terms, and should treat AI RMF as the vocabulary, not the proof. Typical evidence is a public mapping or an assessment report, not a NIST logo. Score it like other voluntary frameworks.",
    lat=39.1403,
    lng=-77.2200,
    related=["iso-42001", "nist-csf", "eu-ai-act"],
    weight=3,
)
