# SOC, ISO, PCI families

ENTRIES = []

def add(**kw):
    ENTRIES.append(kw)

add(
    id="soc-1-type-i",
    name="SOC 1 Type I",
    short="SOC 1 I",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all", "financial"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="A CPA looked at a vendor's financial-reporting controls on one day. The report is for the customer's auditors, not a security badge. Type I does not prove the controls kept working later.",
    elaborate="SOC 1 Type I is an attestation under the AICPA attestation standards (SSAE 18 / AT-C section 320; internationally often paired with ISAE 3402). It reports on controls at a service organization that are relevant to a user entity's internal control over financial reporting (ICFR). A licensed CPA firm examines management's description of the system and opines on whether the description is fairly presented and whether the controls were suitably designed at a specified date. It does not test whether those controls operated effectively over time. That is Type II. The AICPA publishes the standard; it does not 'certify' the company. Typical readers are the customer's external financial-statement auditors, not security reviewers. A SOC 1 does not attest security, availability, or privacy. It does not replace a SOC 2. Scope is often a billing, payroll, payments, or transaction-processing system, not the whole firm. Read the opinion, the carved-out subprocessors, complementary user-entity controls, and the as-of date. A Type I dated last quarter is a snapshot, not a period test. Typical evidence is the full report under NDA. A logo on a marketing page is not the report. Companies sometimes show a SOC 1 when a buyer asked for 'SOC' without specifying; that is the wrong artifact for a security review.",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-1-type-ii", "soc-2-type-ii", "sox"],
    weight=5,
)

add(
    id="soc-1-type-ii",
    name="SOC 1 Type II",
    short="SOC 1 II",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all", "financial"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="Same idea as SOC 1 Type I, but the accountant tested whether the financial-reporting controls actually worked for several months. Still not a security certificate. Customer's financial auditors are the main audience.",
    elaborate="SOC 1 Type II uses the same AICPA AT-C section 320 / SSAE 18 path as Type I, and is the form most user auditors accept. The CPA tests operating effectiveness of ICFR-relevant controls over a review period, commonly six to twelve months. The opinion covers fair presentation of the system description, suitability of design, and operating effectiveness. Exceptions and deviations are listed in the test matrices; a report can be unmodified and still contain exceptions that matter to the user's auditors. Internationally, many of these engagements are also issued under ISAE 3402. This is not a security, privacy, or availability attestation. It does not prove PCI, SOX, or HIPAA. It does not mean the vendor's product is free of material weakness at the customer. Buyers doing security due diligence should ask for SOC 2 Type II instead, and use SOC 1 Type II only when the deal affects the customer's books — payroll, billing, payments, fund administration, claims. Read the period, complementary user-entity controls, subservice organizations (inclusive vs carve-out), and whether a bridge letter covers the gap since period end. Typical evidence is the full Type II report under NDA. A public summary is uncommon; unlike SOC 3 there is no general-use SOC 1. The company cannot truthfully say it is 'SOC 1 certified.'",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-1-type-i", "soc-2-type-ii", "sox"],
    weight=8,
)

add(
    id="soc-2-type-i",
    name="SOC 2 Type I",
    short="SOC 2 I",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all", "cloud"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="An accountant checked that a company's security controls looked properly designed on one date. Nobody proved those controls worked next week. Buyers usually wait for Type II.",
    elaborate="SOC 2 Type I is an attestation under AICPA AT-C section 205 using the Trust Services Criteria (TSC). A CPA firm opines, as of a point in time, on whether management's system description is fairly presented and whether controls were suitably designed to meet the in-scope TSC. Security is required. Availability, confidentiality, processing integrity, and privacy are optional inclusions. Type I does not test operating effectiveness over a period. That is why most enterprise security questionnaires treat Type I as an interim artifact, useful while a first Type II period is running, not as equivalent evidence. The AICPA does not issue the report. Scope, locations, products, and subprocessors are whatever management put in the description. A Type I on a single product is not evidence for the rest of the catalog. It does not prove ISO 27001, does not authorize federal use, and does not mean 'no findings.' Read the as-of date, the TSC categories, carve-outs, and complementary user-entity controls. Typical evidence is the full Type I report under NDA. Marketing that says 'SOC 2 certified' after a Type I is overstating the artifact. If the period for Type II has already closed, ask for Type II instead of accepting a newer Type I.",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-2-type-ii", "soc-3", "soc-2-type-i"],
    weight=6,
)

add(
    id="soc-2-type-ii",
    name="SOC 2 Type II",
    short="SOC 2 II",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all", "cloud"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="An independent accountant tested whether a company's security controls worked over several months. It is a report, not a government license. It does not mean the company cannot be breached.",
    elaborate="SOC 2 Type II is the common U.S. vendor security attestation. A licensed CPA firm examines a described system against the AICPA Trust Services Criteria and reports whether controls were suitably designed and operated effectively over a review period, typically three to twelve months. Security is required. Availability, confidentiality, processing integrity, and privacy appear only if scoped. The AICPA writes the criteria; the CPA firm issues the opinion. This is not a certification, not a regulator approval, and not a penetration-test letter. A clean opinion does not mean every product was in scope, that subprocessors were tested the same way, or that residual risk is acceptable for your use case. Read the system description, test exceptions, complementary user-entity controls, inclusive versus carve-out treatment of subservice organizations, and the period end date. Prefer a recent Type II plus a bridge letter if the period ended more than a few months ago. Typical evidence is the full report under NDA. A SOC 3 is a public summary, not a substitute. 'SOC 2 + HIPAA' and 'SOC 2 Type II AI' are not separate AICPA products. The first is usually a SOC 2 plus a HIPAA mapping or HITRUST; the second is an ordinary SOC 2 whose description mentions AI features. Pair ISO 42001 if you need an AI management-system certificate.",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-2-type-i", "soc-3", "iso-27001", "iso-42001"],
    weight=10,
)

add(
    id="soc-3",
    name="SOC 3",
    short="SOC 3",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all", "cloud"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="A short public version of a SOC 2. You can post it on a website. It leaves out the detailed tests, so a buyer cannot really review the work.",
    elaborate="SOC 3 is a general-use report under the same Trust Services Criteria as SOC 2. The CPA firm's opinion is intended for public distribution. The report describes the system at a high level and states whether the entity maintained effective controls over the review period, but it omits the detailed control descriptions, test procedures, and exception listings that make a SOC 2 Type II useful to a reviewer. Companies publish SOC 3 PDFs on trust pages because they can. A serious GRC review still needs the SOC 2 Type II under NDA. SOC 3 is not a higher bar than SOC 2; it is a less detailed public extract. It is not a certificate and not a regulator mark. If a vendor offers only SOC 3 and refuses SOC 2, treat that as incomplete evidence, not as equivalent assurance. Check that the SOC 3 period and TSC categories match the SOC 2 you later receive. Typical evidence is a downloadable PDF. Some firms also display a SysTrust/WebTrust-style seal; the seal is marketing. The underlying engagement is still a CPA attestation, not an ISO certification and not FedRAMP.",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-2-type-ii", "soc-2-type-i"],
    weight=5,
)

add(
    id="soc-supply-chain",
    name="SOC for Supply Chain",
    short="SOC SC",
    family="SOC",
    kind="attestation",
    geography=["US", "global"],
    industry=["all"],
    issuer="AICPA (CPA firm issues the report)",
    eli5="An accountant report about how a company makes, builds, or ships things — and the controls that protect that system. It is for manufacturers and distributors, not a cloud security badge.",
    elaborate="SOC for Supply Chain is an AICPA attestation for organizations that produce, manufacture, or distribute goods. It uses the Trust Services Criteria plus the AICPA Description Criteria for a Description of an Entity's Production, Manufacturing, or Distribution System. A CPA firm reports on the system that produces or delivers goods and on controls relevant to security, availability, processing integrity, confidentiality, or privacy, as scoped. Type I and Type II forms exist; Type II covers operating effectiveness over a period. This is not SOC 2. A SaaS company that only processes data typically needs SOC 2, not SOC for Supply Chain. Hardware, device, and industrial vendors may hold this when customers want assurance over the build and delivery system, including aspects of integrity that a software SOC 2 does not cover. It is not a product-safety certification, not ISO 9001, and not a government authorization. It does not prove that a finished device is free of defects or that every supplier was audited. Read the system description for what plants, lines, and partners were in scope. Typical evidence is the full report under NDA. Do not treat a SOC 2 logo as this report, or the reverse.",
    lat=40.7580,
    lng=-73.9855,
    related=["soc-2-type-ii", "iso-9001"],
    weight=8,
)

add(
    id="iso-27001",
    name="ISO/IEC 27001",
    short="ISO 27001",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["all"],
    issuer="ISO/IEC; certificate issued by an accredited certification body",
    eli5="A third party checked that the company runs an information-security management system and keeps improving it. The certificate names a scope. If your product is outside that scope, the paper does not cover you.",
    elaborate="ISO/IEC 27001 is the certifiable information security management system (ISMS) standard. The current edition is ISO/IEC 27001:2022. An accredited certification body, not ISO itself, audits and issues a three-year certificate with annual surveillance. The certificate attests that the named organization operates an ISMS for a stated scope — legal entities, locations, and services. It does not attest that a particular SaaS tenant cannot be breached, that every control in Annex A is implemented everywhere, or that personal data is processed lawfully. Annex A is a reference control set; Statement of Applicability decisions matter. Buyers should read the certificate scope, the certification body and accreditation mark (for example UKAS, ANAB, DAkkS), the expiry date, and whether the edition is 2022. A 2013 certificate after the transition window is stale. ISO 27001 is not SOC 2, not FedRAMP, and not a privacy law. It pairs often with ISO 27017 and 27018 for cloud, and with ISO 27701 for privacy. Typical evidence is the certificate PDF plus, under NDA, the statement of applicability or a high-level SoA extract. A 'certified' claim without a scope line is incomplete. Surveillance and recertification dates belong in the file.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27017", "iso-27018", "iso-27701", "iso-22301", "soc-2-type-ii"],
    weight=10,
)

add(
    id="iso-27017",
    name="ISO/IEC 27017",
    short="ISO 27017",
    family="ISO",
    kind="code-of-practice",
    geography=["global"],
    industry=["cloud"],
    issuer="ISO/IEC; typically certified as an extension by an accredited body",
    eli5="Extra cloud-security guidance that sits on top of ISO 27001. It says how a cloud provider and a cloud customer should split the work. It is not a stand-alone gold star.",
    elaborate="ISO/IEC 27017 is a code of practice giving cloud-specific guidance on ISO/IEC 27002 controls, plus additional cloud controls, for both cloud service providers and cloud customers. The commonly cited edition is ISO/IEC 27017:2015. Organizations usually obtain it as an extension to an ISO/IEC 27001 certificate, not as a free-standing management-system certification. It addresses shared responsibility, virtualization, admin rights, customer isolation, and alignment of cloud roles. It does not replace ISO 27001. It does not attest privacy of personal data in the public cloud; that is closer to ISO 27018. It is not CSA STAR, though the topics overlap with the Cloud Controls Matrix. A buyer should confirm the 27017 mark appears on the certificate or in the certification body's scope language, and that the cloud service in the deal is inside that scope. Typical evidence is the ISO 27001 certificate listing 27017, or a separate statement from the certification body. A blog sentence that the company 'follows 27017' without a certificate is a practice claim, not a certification. Combined 27001/27017/27018 certificates are common at large cloud providers.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "iso-27018", "csa-ccm", "csa-star-l2"],
    weight=6,
)

add(
    id="iso-27018",
    name="ISO/IEC 27018",
    short="ISO 27018",
    family="ISO",
    kind="code-of-practice",
    geography=["global"],
    industry=["cloud"],
    issuer="ISO/IEC; typically certified as an extension by an accredited body",
    eli5="Cloud privacy guidance for companies that hold other people's personal data in a public cloud. It rides along with ISO 27001. It is not GDPR and it is not a government permit.",
    elaborate="ISO/IEC 27018 is a code of practice for protecting personally identifiable information (PII) in public clouds acting as PII processors. The commonly cited edition is ISO/IEC 27018:2019. Like 27017, it is usually certified as an extension to ISO/IEC 27001 rather than as its own ISMS. It adds processor-oriented controls: purpose limitation, return and deletion of PII, transparency to the customer, and restrictions on use of customer data for provider marketing. It does not make the provider a GDPR-compliant controller. It does not replace a data processing agreement, SCCs, or a transfer mechanism. It does not cover every privacy law. A company that is a controller, or that processes PII only in a private cloud, may be outside the intended use. Buyers should check that the certificate scope names the cloud service and the processor role, and should still execute a DPA. Typical evidence is the ISO 27001 certificate listing 27018. ISO 27701 is the broader privacy information management system and is the better artifact if you need a PIMS, not only public-cloud processor guidance.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "iso-27017", "iso-27701", "gdpr"],
    weight=6,
)

add(
    id="iso-27701",
    name="ISO/IEC 27701",
    short="ISO 27701",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["all"],
    issuer="ISO/IEC; certificate issued by an accredited certification body",
    eli5="A certificate that the company runs a privacy management system for personal data. The 2019 version hung off ISO 27001. The 2025 version can stand alone. It is not a GDPR certificate from the EU.",
    elaborate="ISO/IEC 27701 specifies a privacy information management system (PIMS) for PII controllers and processors. ISO/IEC 27701:2019 was written as an extension to ISO/IEC 27001 and 27002; most certificates you will still see are 2019 extensions on a 27001 ISMS. ISO/IEC 27701:2025, published 14 October 2025, is a standalone PIMS standard. Transition rules for existing 2019 certificates are set by accreditation and certification bodies; do not assume a date that is not on the paper. The certificate attests that the named scope operates a PIMS. It does not attest legal compliance with GDPR, CPRA, LGPD, or any other statute, and it is not issued by a data-protection authority. It does not replace records of processing, DPIAs, or transfer tools. Buyers should read the scope, whether the organization is certified as controller, processor, or both, the edition year, and the certification body's accreditation. Typical evidence is the certificate PDF. A 'GDPR certified' claim citing only 27701 is overstated. Pair it with the actual transfer mechanism (SCCs, DPF, BCRs) and the DPA. ISO 27018 remains the narrower public-cloud processor code of practice.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "iso-27018", "gdpr", "iso-42001"],
    weight=7,
)

add(
    id="iso-42001",
    name="ISO/IEC 42001",
    short="ISO 42001",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["ai"],
    issuer="ISO/IEC; certificate issued by an accredited certification body",
    eli5="A certificate that the company has a management system for building and using AI on purpose, with roles, risk steps, and reviews. It does not prove a model is fair or safe in your case.",
    elaborate="ISO/IEC 42001:2023 is the certifiable artificial intelligence management system (AIMS) standard. An accredited certification body audits whether the organization has established, implemented, and continually improved an AIMS for a stated scope: AI systems developed, provided, or used. The standard covers AI policy, risk, impact assessment, data for AI systems, lifecycle controls, and supplier relationships. It is not a model card, not a red-team report, and not an EU AI Act conformity assessment. It does not prove a given model is accurate, unbiased, or lawful to deploy in a high-risk use. The EU AI Act is a regulation; 42001 is a voluntary management-system certificate that some organizations use as supporting evidence. 'SOC 2 Type II AI' is not an ISO or AICPA product; if a vendor uses that phrase, ask for the ordinary SOC 2 plus this certificate or a scoped description, not a hybrid brand. Buyers should read the certificate scope (which products, which models, which business units), the certification body, and the expiry. Typical evidence is the certificate PDF. Absence of 42001 is not evidence the vendor has no AI program; presence is not evidence your use case was assessed.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "nist-ai-rmf", "eu-ai-act", "soc-2-type-ii"],
    weight=8,
)

add(
    id="aiuc-1",
    name="AIUC-1",
    short="AIUC-1",
    family="AIUC",
    kind="certification",
    geography=["US", "global"],
    industry=["ai"],
    issuer="Artificial Intelligence Underwriting Company; accredited auditor issues the certificate",
    eli5="An independent audit that an AI agent was tested against a quarterly-updated enterprise standard for security, safety, and reliability. It is not ISO 42001 and not a government license.",
    elaborate="AIUC-1 is a certification against the Artificial Intelligence Underwriting Company’s standard for AI agents. The six pillars are security, safety, reliability, accountability, data and privacy, and societal impact. The company publishes the standard; an accredited auditor issues the certificate. Schellman became the first accredited auditor in February 2026. The standard refreshes quarterly on a fixed calendar (15 January, 15 April, 15 July, 15 October). The edition current on this file is 15 July 2026. It operationalizes ISO 42001, the NIST AI Risk Management Framework, MITRE ATLAS, and the OWASP LLM Top 10 into testable agent practices and technical tests. A typical audit runs four to eight weeks: scoping the named agents, evidence collection, technical evaluation against adversarial scenarios, then the independent auditor’s opinion. To keep the mark, those agents are re-tested quarterly and the engagement is re-audited annually. Scope is usually named products or agent systems, not the whole firm. A certificate on a voice model is not evidence for a coding agent or an unlisted subsidiary. Buyers must read the report: which systems were in scope, which standard version, which practices were tested, and what was carved out. AIUC-1 is not ISO 42001. ISO 42001 certifies an AI management system (AIMS). AIUC-1 certifies that named agents were tested against this agent standard. It is not the NIST AI RMF; that framework issues no certificate. It is not an EU AI Act conformity assessment and not a government license. A logo on a trust page is not the report. Typical evidence is the certificate and the report under NDA. Absence of the mark is not evidence of no agent testing; presence is not evidence your use case was in scope.",
    lat=37.7749,
    lng=-122.4194,
    related=["iso-42001", "nist-ai-rmf", "soc-2-type-ii", "eu-ai-act"],
    weight=8,
)

add(
    id="iso-9001",
    name="ISO 9001",
    short="ISO 9001",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["all"],
    issuer="ISO; certificate issued by an accredited certification body",
    eli5="A quality-management certificate. It says the company has a system for consistent work and complaints, not that its software is secure. Common, and easy to over-read.",
    elaborate="ISO 9001:2015 is the generic quality management system (QMS) standard. An accredited certification body issues a certificate that the named scope runs a QMS meeting 9001 requirements: customer focus, documented processes, corrective action, and improvement. It is not an information-security, privacy, or AI certificate. It does not attest software security, uptime, or lawful processing. Many manufacturers, device makers, and professional-services firms hold it. Software vendors sometimes display it because it is familiar to procurement. A buyer running a security review should not score ISO 9001 as if it were ISO 27001. For medical devices, ISO 13485 is the more specific QMS and should be preferred when that is the industry. Read the scope and expiry. Typical evidence is the certificate. Combined 9001/27001 certificates exist; read each scope. This register gives it a low public-disclosure weight because it is widely held and weakly related to security claims on a trust page.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-13485", "iso-27001", "iso-20000-1"],
    weight=3,
)

add(
    id="iso-22301",
    name="ISO 22301",
    short="ISO 22301",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["all"],
    issuer="ISO; certificate issued by an accredited certification body",
    eli5="A certificate that the company has a business-continuity system: plans for when things break, and practice at those plans. It is not a backup screenshot and not an uptime SLA.",
    elaborate="ISO 22301:2019 is the certifiable business continuity management system (BCMS) standard. An accredited certification body audits whether the organization identifies continuity requirements, runs impact analysis, sets strategies, and exercises plans for a stated scope. The certificate attests the management system, not a particular recovery-time objective on your tenant. It does not replace the contractual SLA, disaster-recovery runbooks, or a SOC 2 availability category. It does not prove the last exercise restored the product you buy. Buyers should read the scope (which services and sites), ask for exercise frequency and last exercise date under NDA, and match RTO/RPO to the contract. Typical evidence is the certificate. Some vendors offer a SOC 2 with availability instead of, or in addition to, 22301. Both can be valid; they are different artifacts. ISO 22301 is not cyber-resilience regulation. EU financial entities under DORA have statutory resilience duties that a 22301 certificate may support but does not discharge.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "dora", "soc-2-type-ii"],
    weight=6,
)

add(
    id="iso-20000-1",
    name="ISO/IEC 20000-1",
    short="ISO 20000-1",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["all", "cloud"],
    issuer="ISO/IEC; certificate issued by an accredited certification body",
    eli5="A certificate that the company manages IT services in a formal way — incidents, changes, service levels. It is not a security audit of the product.",
    elaborate="ISO/IEC 20000-1:2018 is the certifiable IT service management system (SMS) standard. An accredited certification body audits whether the organization plans, designs, delivers, and improves services under a documented SMS for a stated scope. The family is related to ITIL practice but the certificate is to the ISO standard, not to AXELOS/PeopleCert ITIL training. It attests service-management process, not the security of a cloud control plane. It does not replace ISO 27001 or SOC 2. Some public-sector and outsourcing tenders still ask for it. Buyers should read the scope for which services are covered and not infer security testing from a 20000-1 logo. Typical evidence is the certificate. French HDS certification historically leaned on ISO 27001 and, for some activities, service-management evidence; HDS is a separate legal certification. ISO 20000-1 is not a continuity certificate (see 22301) and not a quality certificate (see 9001).",
    lat=46.2044,
    lng=6.1432,
    related=["iso-27001", "iso-9001", "iso-22301", "hds"],
    weight=5,
)

add(
    id="iso-13485",
    name="ISO 13485",
    short="ISO 13485",
    family="ISO",
    kind="certification",
    geography=["global"],
    industry=["healthcare"],
    issuer="ISO; certificate issued by an accredited certification body",
    eli5="A quality-system certificate for medical-device companies. It is about how devices are designed and made, not about a hospital SaaS being HIPAA certified.",
    elaborate="ISO 13485:2016 is the quality management system standard for medical devices and related services. An accredited certification body (often also a regulatory notified-body or MDSAP participant, depending on market) certifies that the named scope runs a device QMS: design control, risk, supplier control, traceability, complaint handling, and documented manufacturing. It is relevant when the vendor is a device manufacturer or a software-as-a-medical-device organization. It is not HIPAA, not HITRUST, and not ISO 27001. A digital health SaaS that is not a device may hold 27001 and not 13485; that can be correct. Conversely, 13485 without a security attestation is a weak answer to a hospital security questionnaire. It does not prove clinical safety of a specific device version, and it is not an FDA 510(k) or CE mark under the EU MDR/IVDR. Buyers should read the scope (which devices or software) and the regulatory scheme the QMS supports. Typical evidence is the certificate. Include this in a security encyclopedia because health-tech vendors routinely list it next to security marks; it is a quality mark, scored as such.",
    lat=46.2044,
    lng=6.1432,
    related=["iso-9001", "hipaa", "hitrust-r2"],
    weight=6,
)

add(
    id="pci-dss",
    name="PCI DSS",
    short="PCI DSS",
    family="PCI",
    kind="certification",
    geography=["global"],
    industry=["payments"],
    issuer="PCI Security Standards Council; validated by a QSA or via SAQ",
    eli5="Rules for companies that store, process, or transmit payment-card data. A qualified assessor or a self-questionnaire checks them. It is about cardholder data, not general privacy.",
    elaborate="The Payment Card Industry Data Security Standard is issued by the PCI Security Standards Council. Current published versions are PCI DSS 4.0 and 4.0.1; 3.2.1 is retired. Payment brands (Visa, Mastercard, American Express, Discover, JCB) decide who must validate and how. Level 1 service providers and many large merchants require an annual Report on Compliance (ROC) by a Qualified Security Assessor (QSA) plus an Attestation of Compliance (AOC). Smaller entities may use a Self-Assessment Questionnaire (SAQ) of the matching type. The standard protects cardholder data and sensitive authentication data. It does not attest general corporate security, HIPAA, or SOC 2. A company can be PCI compliant for a payment environment and weak elsewhere. Scope reduction via a payment processor or P2PE matters; read the AOC for what was in scope. 'PCI certified' is loose talk. Typical evidence is the AOC (often shareable) and, under NDA, the ROC. Check the version, the QSA, the date, and whether the company is a merchant or a service provider. PCI DSS is not PCI 3DS and not the Software Security Framework.",
    lat=42.5030,
    lng=-71.0728,
    related=["pci-3ds", "pci-ssf", "soc-1-type-ii"],
    weight=10,
)

add(
    id="pci-3ds",
    name="PCI 3DS",
    short="PCI 3DS",
    family="PCI",
    kind="certification",
    geography=["global"],
    industry=["payments"],
    issuer="PCI Security Standards Council",
    eli5="A PCI standard for the computers that run 3-D Secure, the extra card-check step at checkout. It is not the same as being PCI DSS compliant for a shop.",
    elaborate="PCI 3DS refers to the PCI 3-D Secure Core Security Standard and related assessment program for environments that operate EMV 3-D Secure components: 3DS Servers, Directory Servers, and Access Control Servers. The PCI Security Standards Council publishes the standard. Assessors qualified for the 3DS program test those environments. Payment brands decide who must validate. This is not PCI DSS, though a 3DS environment may also be in a DSS scope. It is not a merchant 'we use 3-D Secure' badge. A checkout that offers 3-D Secure through a processor does not make the merchant PCI 3DS validated. Typical evidence is a 3DS Attestation of Compliance or listing appropriate to the role. Buyers of 3DS vendor platforms should ask which component was assessed and against which version. Do not treat a PCI DSS AOC as proof of 3DS, or the reverse. The program exists because 3-D Secure systems handle authentication data and protocol security that DSS alone does not fully cover.",
    lat=42.5030,
    lng=-71.0728,
    related=["pci-dss", "pci-ssf"],
    weight=7,
)

add(
    id="pci-ssf",
    name="PCI Software Security Framework",
    short="PCI SSF",
    family="PCI",
    kind="certification",
    geography=["global"],
    industry=["payments"],
    issuer="PCI Security Standards Council",
    eli5="PCI's modern program for payment software and for how that software is built. It replaced the old PA-DSS listing for payment applications. Two standards sit inside it.",
    elaborate="The PCI Software Security Framework (SSF) is the PCI SSC's program for payment software security. It contains two standards. The Secure Software Standard is used to validate specific payment software products; successful products are listed as Validated Payment Software. The Secure Software Lifecycle (Secure SLC) Standard is used to validate a vendor's secure development and maintenance process; successful vendors are listed as Secure SLC Qualified Vendors. SSF Assessor Companies, qualified by PCI SSC, perform the assessments. SSF succeeds PA-DSS for payment applications; PA-DSS is retired and should not be claimed as current. SSF is not PCI DSS. A merchant's DSS AOC does not list software. A software vendor can hold SSF listings and still need DSS if it also stores card data as a service provider. Typical evidence is the PCI SSC public listing plus the report on validation where shareable. Read which standard, which product version, and the expiry. 'PCI certified software' without a listing URL is incomplete.",
    lat=42.5030,
    lng=-71.0728,
    related=["pci-dss", "pci-3ds"],
    weight=7,
)
