ENTRIES = []

def add(**kw):
    ENTRIES.append(kw)

add(
    id="tisax",
    name="TISAX",
    short="TISAX",
    family="TISAX",
    kind="attestation",
    geography=["DE", "EU"],
    industry=["automotive"],
    issuer="ENX Association (VDA ISA catalog)",
    eli5="A German-born car-industry assessment. A supplier gets labels on the ENX portal after an approved auditor checks them. Partners look it up there. A PDF on a website is not the point.",
    elaborate="Trusted Information Security Assessment Exchange is the automotive information-security assessment scheme governed by the ENX Association, using the VDA ISA (Information Security Assessment) catalog, which is closely aligned with ISO/IEC 27001. Participants receive TISAX labels (for example Info high, prototype protection, data) at Assessment Levels AL2 (typically remote plausibility check) or AL3 (on-site). AL1 is a self-assessment and does not produce a shareable TISAX label. Results are exchanged on the ENX portal among participants, not primarily via a public certificate. TISAX is not ISO 27001, though many companies hold both. It is not a general cloud authorization. Typical evidence is a TISAX scope ID and labels visible to the partner on the ENX portal, plus the assessment result report if the participant shares it. A marketing badge without a scope ID is weak. Validity is commonly three years; confirm on the portal. Score it as industry-specific independent assurance.",
    lat=50.1109,
    lng=8.6821,
    related=["iso-27001", "c5"],
    weight=8,
)

add(
    id="c5",
    name="BSI C5",
    short="C5",
    family="C5",
    kind="attestation",
    geography=["DE"],
    industry=["cloud", "public-sector"],
    issuer="BSI (catalog); independent auditor issues the attestation",
    eli5="Germany's cloud-security criteria catalog from the BSI. An auditor writes a report, often like a SOC report. The BSI does not stamp your company. Customers are supposed to read the report.",
    elaborate="The Cloud Computing Compliance Criteria Catalogue (C5) is published by Germany's Federal Office for Information Security (BSI). Current widely used edition is C5:2020; BSI has been revising the catalog (including work toward a later edition). C5 is not a BSI-issued certificate. An independent auditor attests against the criteria, commonly under ISAE 3000, as Type 1 (design at a date) or Type 2 (operating effectiveness over a period). BSI states it does not select auditors or review reports; the customer must read the report. Criteria split into basic and additional requirements across 17 areas, mapped to ISO 27001 and other sources. German public-sector and, in health, statutory cloud rules have increasingly pointed at C5 Type 2 — verify the current legal pointer for your sector. C5 is not FedRAMP and not ISO 27001, though a combined C5/SOC 2 report is common. Typical evidence is the C5 attestation report under NDA. A logo is not the report. Prefer Type 2.",
    lat=50.7374,
    lng=7.0982,
    related=["iso-27001", "soc-2-type-ii", "ens", "tisax"],
    weight=9,
)

add(
    id="ens",
    name="ENS",
    short="ENS",
    family="ENS",
    kind="certification",
    geography=["ES"],
    industry=["public-sector", "cloud"],
    issuer="Centro Criptológico Nacional (Spain); certificates by accredited bodies",
    eli5="Spain's National Security Scheme for systems that handle government information. Companies get certified at a level: basic, medium, or high. Needed for a lot of Spanish public-sector work.",
    elaborate="The Esquema Nacional de Seguridad is Spain's National Security Framework, currently set out in Royal Decree 311/2022. The Centro Criptológico Nacional (CCN) publishes CCN-STIC guidance. Systems are categorized Básico, Medio, or Alto. Certification is performed by bodies accredited for ENS, not by a blogger and not by ISO automatically. Cloud and SaaS vendors that sell to Spanish public bodies often hold ENS certification for a named service. ENS is not ISO 27001, though 27001 helps. It is not EU-wide. Typical evidence is the ENS certificate stating category and scope. A claim of 'aligned to ENS' without a certificate is a self-statement. Score it as a national government certification, similar in spirit to C5 or SecNumCloud but distinct.",
    lat=40.4168,
    lng=-3.7038,
    related=["c5", "iso-27001", "fedramp"],
    weight=8,
)

add(
    id="cyber-essentials",
    name="Cyber Essentials",
    short="CE",
    family="Cyber-Essentials",
    kind="certification",
    geography=["GB"],
    industry=["all", "public-sector"],
    issuer="UK National Cyber Security Centre; delivered via IASME consortium",
    eli5="A short UK government cyber hygiene scheme. The company answers questions about five basic controls. A person can get the badge without an on-site hack-test. Plus is the tested version.",
    elaborate="Cyber Essentials is a UK scheme owned by the National Cyber Security Centre and operated through the IASME consortium and licensed certification bodies. It covers five technical control themes: firewalls, secure configuration, user access control, malware protection, and security update management. The base certificate is a self-assessment that is verified by a certification body; it is not a penetration test. UK government contracts often require at least Cyber Essentials. It is not ISO 27001 and not SOC 2. Typical evidence is the certificate and the listing on the NCSC/IASME registry. Validity is one year. Cyber Essentials Plus is a separate, hands-on assessed certificate. Do not score base CE as Plus. Scope (which legal entity and which network) matters; a group badge may not cover the product environment.",
    lat=51.5074,
    lng=-0.1278,
    related=["cyber-essentials-plus", "iso-27001"],
    weight=4,
)

add(
    id="cyber-essentials-plus",
    name="Cyber Essentials Plus",
    short="CE+",
    family="Cyber-Essentials",
    kind="certification",
    geography=["GB"],
    industry=["all", "public-sector"],
    issuer="UK National Cyber Security Centre; delivered via IASME consortium",
    eli5="The tested version of Cyber Essentials. An assessor actually checks the five basic controls, including vulnerability scans. Still a hygiene certificate, not a full ISO audit.",
    elaborate="Cyber Essentials Plus adds an independent technical assessment to the Cyber Essentials control set, including vulnerability scanning of in-scope systems and checks that the five themes work in practice. It is still a bounded hygiene scheme, not an ISMS certificate and not a SOC 2. UK public-sector and some regulated buyers ask for Plus rather than the base badge. Typical evidence is the Plus certificate and registry listing. Validity is one year. A base Cyber Essentials certificate is not Plus. Scope limitations apply; a scan that excluded production cloud accounts is a problem. Score Plus above base CE and well below ISO 27001.",
    lat=51.5074,
    lng=-0.1278,
    related=["cyber-essentials", "iso-27001"],
    weight=6,
)

add(
    id="irap",
    name="IRAP",
    short="IRAP",
    family="IRAP",
    kind="attestation",
    geography=["AU"],
    industry=["public-sector", "cloud"],
    issuer="Australian Signals Directorate (assessors); consuming agency accepts the assessment",
    eli5="Australia's program of registered assessors who check systems against the government's information-security manual. ASD does not hand you a consumer certificate. An agency decides whether to accept the report.",
    elaborate="The Information Security Registered Assessors Program is run by the Australian Signals Directorate. IRAP assessors independently assess systems against the Australian Government Information Security Manual (ISM) and related guidance. ASD endorses assessors; it does not issue a public 'IRAP certified' consumer mark for a SaaS brand. A consuming Australian government agency decides whether to accept the assessment for a classification (commonly Official or Protected for commercial cloud). Typical evidence is an IRAP assessment report and the agency's acceptance, plus any ASD or buyer listing of assessed services. Cloud hyperscalers publish which regions and services have been IRAP-assessed. A marketing line 'IRAP certified' without a classification, assessor, and service list is overstated. IRAP is not FedRAMP. It is not Essential Eight certification — Essential Eight is a different ASD maturity model. Score a documented Protected assessment high for Australian public sector.",
    lat=-35.2809,
    lng=149.1300,
    related=["fedramp", "ismap", "nist-800-53"],
    weight=10,
)

add(
    id="ismap",
    name="ISMAP",
    short="ISMAP",
    family="ISMAP",
    kind="certification",
    geography=["JP"],
    industry=["public-sector", "cloud"],
    issuer="ISMAP Steering Committee (Digital Agency / METI / MIC / NISC)",
    eli5="Japan's government cloud-security register. A cloud service is audited and then listed if it passes. If it is not on the list, it is not ISMAP.",
    elaborate="The Information system Security Management and Assessment Program is Japan's government program for assessing cloud services used in government information systems. The ISMAP Steering Committee (Digital Agency, METI, MIC, NISC and related bodies) governs it. Registered audit organizations assess services against the ISMAP control set; successful services appear on the ISMAP Cloud Service List. There is also ISMAP-LIU for lower-impact use, which is a lighter listing — read which list the service is on. ISMAP is not ISO 27001, though 27001 is typically part of the evidence pile. It is not FedRAMP. Typical evidence is the service's presence on the official ISMAP list, with the registered date and scope. A Japanese-language 'ISMAP aligned' slide is not a listing. Score a live listing as a national government cloud authorization.",
    lat=35.6762,
    lng=139.6503,
    related=["irap", "fedramp", "mtcs", "k-isms"],
    weight=9,
    note="ISMAP-LIU is a related lighter listing; confirm on the official list rather than treating it as full ISMAP.",
)

add(
    id="mtcs",
    name="MTCS",
    short="MTCS",
    family="MTCS",
    kind="certification",
    geography=["SG"],
    industry=["cloud"],
    issuer="IMDA Singapore (SS 584); certified by accredited bodies",
    eli5="Singapore's multi-tier cloud security standard. Providers get certified at Level 1, 2, or 3. Level 3 is the strictest. It is a real certificate, not just the PDPA law.",
    elaborate="The Multi-Tier Cloud Security standard is Singapore Standard SS 584, under the Infocomm Media Development Authority. Certification bodies audit cloud providers to one of three tiers (Level 1 baseline through Level 3). The certificate names the service and the level. MTCS is not the PDPA. It is not CSA STAR, though topics overlap. Typical evidence is the MTCS certificate and any IMDA or certification-body listing. Read the level and the service name. A Level 1 certificate is not Level 3. Score it as a national cloud certification, below IRAP/FedRAMP in this register because the buyer population is narrower, but it is independent assurance.",
    lat=1.3521,
    lng=103.8198,
    related=["pdpa-sg", "ismap", "k-isms", "csa-star-l2"],
    weight=7,
)

add(
    id="k-isms",
    name="K-ISMS",
    short="K-ISMS",
    family="K-ISMS",
    kind="certification",
    geography=["KR"],
    industry=["all", "cloud"],
    issuer="Korea Internet & Security Agency (KISA) / Ministry of Science and ICT",
    eli5="South Korea's information-security management certification. Required for a lot of Korean public and large-service work. Related to ISO 27001 but it is a Korean legal scheme.",
    elaborate="K-ISMS is the Korean Information Security Management System certification operated with KISA under Korean law (the Information and Communications Network Act framework and related rules). It certifies that an organization operates an ISMS meeting the Korean control set. It is influenced by ISO/IEC 27001 but is not the same certificate. Korea also operates a cloud-specific scheme (often referred to in English as CSAP / cloud security assurance) that is distinct; do not merge them. Typical evidence is the K-ISMS certificate issued in the Korean program, with scope and validity. A global ISO 27001 certificate is not K-ISMS. Score K-ISMS as a national ISMS certification when the buyer is Korean public sector or a regulated Korean service.",
    lat=37.5665,
    lng=126.9780,
    related=["iso-27001", "ismap", "mtcs"],
    weight=8,
    note="Korea's cloud CSAP is a separate scheme; not merged into this entry.",
)

add(
    id="dora",
    name="DORA",
    short="DORA",
    family="EU-digital",
    kind="regulation",
    geography=["EU"],
    industry=["financial"],
    issuer="European Union (Regulation (EU) 2022/2554); ESAs and national competent authorities",
    eli5="An EU law that says banks and other financial firms, and their important tech suppliers, must be operationally resilient. It is not a vendor certificate you can download.",
    elaborate="The Digital Operational Resilience Act (Regulation (EU) 2022/2554) has applied since 17 January 2025. It imposes ICT risk, incident, testing, and third-party duties on financial entities and, for critical ICT third-party providers, a Union-level oversight regime under the European Supervisory Authorities. It is law, not a certification. A vendor cannot 'be DORA certified.' A financial entity can require contractual clauses, registers of information, and testing cooperation. Oversight of designated critical ICT third-party providers is a public process, not a logo. Typical evidence is contract language and, if the provider is designated, the oversight relationship — not a certificate PDF. ISO 22301 and SOC 2 may support a program; they do not discharge DORA. Weight is moderate as a disclosure claim because it is newly fashionable on trust pages and usually unverified.",
    lat=50.8503,
    lng=4.3517,
    related=["nis2", "iso-22301", "soc-2-type-ii"],
    weight=4,
)

add(
    id="nis2",
    name="NIS2",
    short="NIS2",
    family="EU-digital",
    kind="regulation",
    geography=["EU"],
    industry=["all"],
    issuer="European Union (Directive (EU) 2022/2555); implemented by member states",
    eli5="An EU directive that makes more essential and important entities, and some of their suppliers, meet cybersecurity duties. Each country writes it into national law. Not a certificate.",
    elaborate="The NIS2 Directive (EU) 2022/2555 replaces the first NIS Directive and expands the set of essential and important entities. Member states transpose it into national law; the transposition deadline was 17 October 2024, and national implementations differ. It is not a vendor certification. There is no 'NIS2 certificate' issued by the Commission. Some countries overlay national schemes (for example, existing essential-service security laws). A SaaS vendor may be in scope as an important entity or as a supplier that gets contractual flow-down. Typical evidence is none as a cert. A trust-page badge is a claim. Pair with national schemes (C5, ENS, Cyber Essentials) when those are the actual artifacts. Weight is low.",
    lat=50.8503,
    lng=4.3517,
    related=["dora", "c5", "ens", "cyber-essentials"],
    weight=3,
)

add(
    id="eu-ai-act",
    name="EU AI Act",
    short="EU AI Act",
    family="EU-digital",
    kind="regulation",
    geography=["EU"],
    industry=["ai"],
    issuer="European Union (Regulation (EU) 2024/1689); AI Office and national market-surveillance authorities",
    eli5="The European Union's law for AI systems, with bans, high-risk duties, and rules for general-purpose models. It is a statute. ISO 42001 is not the same thing.",
    elaborate="Regulation (EU) 2024/1689, the AI Act, is EU law. It uses a risk-based scheme: prohibited practices, high-risk systems with conformity duties, transparency rules, and obligations for general-purpose AI models. Application is phased after entry into force in 2024; do not treat a vendor as 'AI Act certified.' Conformity assessment for high-risk systems, when required, is a regulated product process, not a SOC 2. ISO/IEC 42001 may be used as a management-system input; it is not an EU AI Act certificate. The EU AI Office and national market-surveillance authorities have roles that differ by provision. Typical evidence is none as a cert on a trust page. A GPAI model card or a high-risk technical file, if they exist, are the real artifacts. Weight is low as a claimed badge and high as a legal duty when the product is actually in a regulated class — this register scores the badge.",
    lat=50.8503,
    lng=4.3517,
    related=["iso-42001", "nist-ai-rmf"],
    weight=3,
)

add(
    id="cis-controls",
    name="CIS Controls",
    short="CIS Controls",
    family="CIS",
    kind="framework",
    geography=["global"],
    industry=["all"],
    issuer="Center for Internet Security",
    eli5="A prioritized list of security safeguards from the Center for Internet Security, in implementation groups. Anyone can adopt them. CIS does not certify your whole company for listing them.",
    elaborate="The CIS Critical Security Controls are a prioritized set of safeguards published by the Center for Internet Security. Version 8 / 8.1 organizes controls into Implementation Groups IG1, IG2, and IG3. Organizations adopt them as a baseline. CIS offers related products (CSAT self-assessment, CIS Benchmarks for hardening, and some independently assessed Benchmark programs). There is no general 'CIS Controls certified company' mark equivalent to ISO 27001. A trust page that says 'CIS Controls aligned' is a mapping claim. Typical evidence is a scored CSAT or an independent assessment against a stated IG, not a CIS corporate seal. Benchmarks (for example CIS Amazon Linux) are product-hardening artifacts, not an organization certificate. Score the framework low unless a third party tested a stated IG.",
    lat=42.5906,
    lng=-73.7020,
    related=["nist-csf", "iso-27001", "sig"],
    weight=3,
)

add(
    id="sox",
    name="Sarbanes-Oxley Act",
    short="SOX",
    family="SOX",
    kind="regulation",
    geography=["US"],
    industry=["financial"],
    issuer="United States Congress; SEC and PCAOB oversee public-company reporting",
    eli5="A U.S. law for public companies about honest books and the controls around those books. A private SaaS vendor is not 'SOX certified.' They might give you a SOC 1 so your auditors can do their SOX work.",
    elaborate="The Sarbanes-Oxley Act of 2002 is U.S. federal law. Sections 302 and 404 are the ones GRC people mean: executive certification of reports and management's assessment of internal control over financial reporting, with an auditor's attestation for most issuers. The SEC administers the reporting regime; the PCAOB oversees the audit firms. SOX is not a vendor certification. A private company cannot hold SOX. A public vendor is subject to SOX for its own filings; that does not attest the security of a product it sells. What vendors correctly provide is a SOC 1 Type II so a customer's financial auditors can rely on ICFR-relevant controls. Typical evidence of 'SOX support' is that SOC 1, not a SOX certificate. Weight is low as a trust-page badge and the entry exists so the register can say this plainly.",
    lat=38.9072,
    lng=-77.0369,
    related=["soc-1-type-ii", "soc-1-type-i"],
    weight=2,
)

add(
    id="hds",
    name="HDS",
    short="HDS",
    family="HDS",
    kind="certification",
    geography=["FR"],
    industry=["healthcare"],
    issuer="Agence du Numérique en Santé; certificates by COFRAC-accredited bodies",
    eli5="A French legal certificate required to host other people's health data. Built on ISO 27001 plus extra health and sovereignty rules. Hospitals in France will ask for it by name.",
    elaborate="Hébergeur de Données de Santé is the French certification for hosting personal health data on behalf of others, under the Public Health Code (including article R1111-10 and related decrees). The Agence du Numérique en Santé publishes the certification and accreditation référentiels. Certification bodies accredited by COFRAC (or an equivalent European accreditation body) issue the certificate, typically for three years with surveillance. The scheme requires an ISO/IEC 27001 ISMS covering the hosting activities, plus HDS-specific contract, transparency, and sovereignty requirements. It replaced the older ministerial agrément. It is not HIPAA and not HITRUST. A U.S. HIPAA BAA does not satisfy HDS. Typical evidence is the HDS certificate naming activities and scope. French health buyers will look this up. Score it as a statutory national health-hosting certification.",
    lat=48.8566,
    lng=2.3522,
    related=["iso-27001", "hipaa", "hitrust-r2", "iso-20000-1"],
    weight=9,
)
