ENTRIES = []

def add(**kw):
    ENTRIES.append(kw)

add(
    id="gdpr",
    name="GDPR",
    short="GDPR",
    family="GDPR",
    kind="regulation",
    geography=["EU"],
    industry=["all"],
    issuer="European Union (Regulation (EU) 2016/679); supervised by member-state authorities and the EDPB",
    eli5="The European Union's main privacy law. Every company that falls under it must follow it. There is no GDPR certificate. A badge that says 'GDPR certified' is advertising.",
    elaborate="The General Data Protection Regulation (EU) 2016/679 has applied since 25 May 2018. It is law, not a vendor certification. Supervisory authorities in member states enforce it; the European Data Protection Board coordinates. Controllers and processors that are in scope must meet the Regulation's duties. Article 42 allows certification mechanisms, but there is no single EU-wide 'GDPR certificate' that a SaaS vendor typically holds, and ISO 27701 is not a GDPR certificate. A DPA, a RoPA, SCCs, BCRs, or a DPF listing are tools, not substitutes for the law. A trust-page badge does not move a serious score. This register still includes GDPR because nearly every B2B page claims it, and buyers need a clerk's reminder: ask for the legal mechanism and the DPA, not a logo. Typical evidence of a program — not of 'holding GDPR' — is a DPA, transfer tool, and, if offered, ISO 27701. Weight is low because presence on a page is nearly universal and unverifiable as a cert.",
    lat=50.8503,
    lng=4.3517,
    related=["uk-gdpr", "eprivacy", "iso-27701", "scc", "bcr", "eu-us-dpf"],
    weight=3,
)

add(
    id="uk-gdpr",
    name="UK GDPR",
    short="UK GDPR",
    family="GDPR",
    kind="regulation",
    geography=["GB"],
    industry=["all"],
    issuer="United Kingdom (retained/reformed UK GDPR); Information Commissioner's Office",
    eli5="The United Kingdom's version of the GDPR, kept after Brexit and run by the ICO. Still a law, not a certificate you can hang on the wall.",
    elaborate="The UK GDPR is the United Kingdom's data-protection law, based on the EU GDPR as retained and amended after Brexit, read with the Data Protection Act 2018. The Information Commissioner's Office is the supervisor. It is not the EU GDPR. Transfers between the UK and the EU currently benefit from adequacy arrangements in both directions, but those are political instruments and can change; do not treat them as a vendor certificate. UK IDTA or the UK Addendum to the EU SCCs are the common contract tools when adequacy does not apply. There is no 'UK GDPR certified' mark from the ICO that a SaaS vendor holds as a product. Typical evidence is a UK-appropriate DPA and transfer tool. Score it as a regulation, like GDPR. A company can be in scope of both EU GDPR and UK GDPR at once.",
    lat=51.5074,
    lng=-0.1278,
    related=["gdpr", "eprivacy", "scc", "eu-us-dpf"],
    weight=3,
)

add(
    id="eprivacy",
    name="ePrivacy Directive",
    short="ePrivacy",
    family="GDPR",
    kind="regulation",
    geography=["EU"],
    industry=["all"],
    issuer="European Union (Directive 2002/58/EC as amended); implemented by member states",
    eli5="An older EU rule about communications privacy and cookies, implemented differently in each country. The proposed ePrivacy Regulation never became the new law. This is not a vendor certificate.",
    elaborate="The ePrivacy Directive (2002/58/EC), as amended, is EU law on privacy of electronic communications: traffic data, marketing, and storage of information on a subscriber's device (the 'cookie' rule). Member states implemented it in national law, so the details differ. A proposed ePrivacy Regulation has not replaced it. This is not a certification. Cookie banners and consent tools are not attestations and are out of scope for this register as products. The entry exists so a GRC reader can see why a trust page that says 'ePrivacy compliant' is making a legal claim, not showing an audit. Typical evidence is none as a cert. Weight is low. Do not confuse this with GDPR; they interact, especially on consent and electronic marketing.",
    lat=50.8503,
    lng=4.3517,
    related=["gdpr", "uk-gdpr"],
    weight=2,
)

add(
    id="ccpa-cpra",
    name="CCPA / CPRA",
    short="CPRA",
    family="US-privacy",
    kind="regulation",
    geography=["US"],
    industry=["all"],
    issuer="State of California; California Privacy Protection Agency and Attorney General",
    eli5="California's consumer privacy law, as expanded by the CPRA. If a company is in scope, it must follow the statute. There is no California privacy certificate for vendors.",
    elaborate="The California Consumer Privacy Act of 2018, as amended by the California Privacy Rights Act (Proposition 24, operative for most provisions in 2023), is state law. The California Privacy Protection Agency and the Attorney General enforce. It creates consumer rights and business duties for entities that meet thresholds or process data in specified ways. It is not a certification. A 'CCPA compliant' badge is a claim. Service-provider and contractor contract language matters more than a logo. The CPRA is the amendment; modern references should be to the amended CCPA, not to a separate certificate called CPRA. This is not GDPR. Typical evidence is contract terms and a privacy notice, not a cert PDF. Weight is low for the same reason as GDPR: nearly everyone in a B2B directory claims it, and it is not third-party assurance.",
    lat=38.5816,
    lng=-121.4944,
    related=["vcdpa", "us-state-privacy", "gdpr"],
    weight=3,
)

add(
    id="vcdpa",
    name="VCDPA",
    short="VCDPA",
    family="US-privacy",
    kind="regulation",
    geography=["US"],
    industry=["all"],
    issuer="Commonwealth of Virginia; Attorney General",
    eli5="Virginia's consumer data-protection act. Another state privacy law. No certificate. The Attorney General enforces it.",
    elaborate="The Virginia Consumer Data Protection Act is Virginia state law, effective 1 January 2023. The Attorney General enforces. It is a controller/processor statute with rights, duties, and a 30-day right-to-cure that has been part of the statute's enforcement design. It is not a certification. It is not the CCPA. A vendor cannot 'hold VCDPA.' This entry is the named example the register was asked to carry; the rest of the U.S. state cohort sits under us-state-privacy. Typical evidence is none as a cert. Include it on a trust page only as a legal scope statement.",
    lat=37.5407,
    lng=-77.4360,
    related=["ccpa-cpra", "us-state-privacy"],
    weight=2,
)

add(
    id="us-state-privacy",
    name="U.S. state consumer privacy laws",
    short="US state privacy",
    family="US-privacy",
    kind="regulation",
    geography=["US"],
    industry=["all"],
    issuer="Individual U.S. states",
    eli5="A growing pile of state privacy laws that look a bit like each other but are not the same. None of them issue a vendor certificate. California and Virginia have their own entries.",
    elaborate="Besides California and Virginia, many U.S. states have enacted comprehensive consumer privacy statutes (Colorado CPA, Connecticut CTDPA, Utah UCPA, Texas TDPSA, Oregon, Montana, and others — the set grows). They are laws, not certifications. They differ on thresholds, employee data, appeals, enforcement, and cure periods. A trust page that lists ten state acronyms is making a legal coverage claim. There is no 'U.S. state privacy certified' mark. Typical evidence is contract terms and a notice, not a cert. This family entry exists so the register does not pretend each state law is a separate assurance product. Score the family once. For California and Virginia, see the dedicated entries. Do not invent a national U.S. privacy certificate.",
    lat=38.9072,
    lng=-77.0369,
    related=["ccpa-cpra", "vcdpa"],
    weight=2,
)

add(
    id="pipeda",
    name="PIPEDA",
    short="PIPEDA",
    family="privacy-national",
    kind="regulation",
    geography=["CA"],
    industry=["all"],
    issuer="Canada (federal); Office of the Privacy Commissioner of Canada",
    eli5="Canada's federal private-sector privacy law. Provinces can have their own substantially similar laws. There is no PIPEDA certificate.",
    elaborate="The Personal Information Protection and Electronic Documents Act is Canada's federal private-sector privacy statute, overseen by the Office of the Privacy Commissioner of Canada. Some provinces have substantially similar private-sector laws (for example Alberta, British Columbia, and Quebec's Law 25 / Law 14 regime, which is stricter and separate). PIPEDA is not a certification. A vendor cannot hold PIPEDA. Adequacy conversations with the EU are a government matter, not a vendor badge. Typical evidence is a Canadian DPA and program description. Weight is low. Do not treat a Canadian privacy policy as an attestation.",
    lat=45.4215,
    lng=-75.6972,
    related=["gdpr", "lgpd", "ccpa-cpra"],
    weight=3,
)

add(
    id="lgpd",
    name="LGPD",
    short="LGPD",
    family="privacy-national",
    kind="regulation",
    geography=["BR"],
    industry=["all"],
    issuer="Brazil (Lei nº 13.709/2018); Autoridade Nacional de Proteção de Dados",
    eli5="Brazil's general data-protection law. The national authority is the ANPD. It is a law, not a certificate a vendor can buy.",
    elaborate="The Lei Geral de Proteção de Dados Pessoais (Law 13.709/2018) is Brazil's general data-protection statute. The Autoridade Nacional de Proteção de Dados (ANPD) is the supervisor. It is not a certification. Agent roles (controller/operator) and transfer tools are legal constructs. A 'LGPD compliant' badge is a claim. Typical evidence is a Brazilian-law DPA and, if used, a transfer mechanism recognized under the statute. Weight is low. Do not treat ISO 27701 as an ANPD certificate.",
    lat=-15.7975,
    lng=-47.8919,
    related=["gdpr", "pipeda", "iso-27701"],
    weight=3,
)

add(
    id="pdpa-sg",
    name="PDPA (Singapore)",
    short="PDPA SG",
    family="privacy-national",
    kind="regulation",
    geography=["SG"],
    industry=["all"],
    issuer="Singapore; Personal Data Protection Commission",
    eli5="Singapore's personal-data law, enforced by the PDPC. Not the same law as Thailand's PDPA. Not a certificate.",
    elaborate="Singapore's Personal Data Protection Act is national law, administered by the Personal Data Protection Commission (PDPC). It is not Thailand's PDPA and not Malaysia's PDPA. It is not a certification, though Singapore also has other cyber marks (for example Cyber Trust / Cyber Essentials-style marks under CSA Singapore) that are separate from the statute. A vendor cannot hold PDPA. Typical evidence is a Singapore-law processing agreement and a PDPC-aligned notice. Weight is low. MTCS is the Singapore cloud security standard and is a different entry.",
    lat=1.3521,
    lng=103.8198,
    related=["pdpa-th", "mtcs", "gdpr"],
    weight=3,
)

add(
    id="pdpa-th",
    name="PDPA (Thailand)",
    short="PDPA TH",
    family="privacy-national",
    kind="regulation",
    geography=["TH"],
    industry=["all"],
    issuer="Thailand; Office of the Personal Data Protection Committee",
    eli5="Thailand's personal-data law. Same acronym as Singapore's, different country and different statute. Still not a certificate.",
    elaborate="Thailand's Personal Data Protection Act B.E. 2562 (2019) is national law. The Office of the Personal Data Protection Committee (PDPC) is the supervisor. It shares an English acronym with Singapore's PDPA and must not be merged with it. It is not a certification. A trust page that says 'PDPA' without a country is ambiguous. Typical evidence is a Thailand-law processing agreement. Weight is low. This entry exists so the register does not collapse two statutes.",
    lat=13.7563,
    lng=100.5018,
    related=["pdpa-sg", "gdpr"],
    weight=2,
)

add(
    id="csa-star-l1",
    name="CSA STAR Level 1",
    short="STAR L1",
    family="CSA",
    kind="attestation",
    geography=["global"],
    industry=["cloud"],
    issuer="Cloud Security Alliance",
    eli5="A cloud company fills out the CSA questionnaire and publishes it in the STAR registry. Nobody independent had to audit it. Useful transparency, weak assurance.",
    elaborate="CSA STAR Level 1 is a self-assessment. The provider completes the Consensus Assessments Initiative Questionnaire (CAIQ / STAR Level 1 Security Questionnaire) based on the Cloud Controls Matrix and submits it to the CSA STAR Registry. CSA may offer optional automated checks (Valid-AI-ted) on submissions; that is not a third-party audit of the cloud service. Level 1 is transparency, not certification. Anyone can publish a CAIQ. Buyers should open the registry entry, read the date, and treat answers as claims. Typical evidence is the public STAR Registry URL. STAR Level 2 is the audited tier. Do not score Level 1 as if it were ISO 27001 or SOC 2. The underlying questionnaire is also catalogued as caiq.",
    lat=47.6062,
    lng=-122.3321,
    related=["caiq", "csa-ccm", "csa-star-l2"],
    weight=4,
)

add(
    id="csa-star-l2",
    name="CSA STAR Level 2",
    short="STAR L2",
    family="CSA",
    kind="certification",
    geography=["global"],
    industry=["cloud"],
    issuer="Cloud Security Alliance (via accredited certification bodies or CPA firms)",
    eli5="A third party audits a cloud provider against the CSA cloud-control set, usually on top of ISO 27001 or SOC 2. Stronger than the self-filled Level 1 form.",
    elaborate="CSA STAR Level 2 is third-party assurance against the Cloud Controls Matrix. Two common shapes exist: STAR Certification, an extension of ISO/IEC 27001 performed by a certification body, and STAR Attestation, a SOC 2 engagement that includes CCM criteria, performed by a CPA firm. Both should be visible in the STAR Registry. Level 2 is not Level 1. Level 3 (continuous auditing) has been described by CSA for years and is rarely what a B2B buyer is looking at on a trust page; do not assume a vendor has it. STAR Certification generally expects an ISO 27001 ISMS. Typical evidence is the STAR Registry entry plus the ISO certificate or SOC 2/STAR attestation report. A self-published CAIQ is not Level 2. Score Level 2 with other independent cloud attestations, below FedRAMP.",
    lat=47.6062,
    lng=-122.3321,
    related=["csa-star-l1", "csa-ccm", "iso-27001", "soc-2-type-ii"],
    weight=8,
)

add(
    id="csa-ccm",
    name="CSA Cloud Controls Matrix",
    short="CSA CCM",
    family="CSA",
    kind="framework",
    geography=["global"],
    industry=["cloud"],
    issuer="Cloud Security Alliance",
    eli5="CSA's list of cloud security controls. It is the library behind STAR and CAIQ. A company can map to it. Mapping is not a certificate.",
    elaborate="The Cloud Controls Matrix is CSA's cloud security control framework. Current published editions in wide use are CCM v4 and v4.1 (CSA has published v4.1 with a transition path for STAR submissions). It organizes controls across cloud domains and maps to other standards. It is not a certification. STAR Level 1 and Level 2 use it. Buyers should not accept 'we follow CCM' as assurance. Typical evidence is a STAR Registry entry or an independent report that tested CCM controls. ISO 27017 and CCM overlap in topic, not in issuance. Score the framework low; score STAR Level 2 or ISO 27001 when those exist.",
    lat=47.6062,
    lng=-122.3321,
    related=["caiq", "csa-star-l1", "csa-star-l2", "iso-27017"],
    weight=3,
)

add(
    id="caiq",
    name="CAIQ",
    short="CAIQ",
    family="CSA",
    kind="questionnaire",
    geography=["global"],
    industry=["cloud"],
    issuer="Cloud Security Alliance",
    eli5="A long yes/no questionnaire CSA wrote so buyers can ask cloud vendors the same security questions. Filling it out is not a certification.",
    elaborate="The Consensus Assessments Initiative Questionnaire is CSA's question set derived from the Cloud Controls Matrix. The version submitted to the STAR Registry is the STAR Level 1 Security Questionnaire (CAIQ v4 / v4.1 as specified by CSA). It is a questionnaire, not a certification. Providers answer it for the registry or send it to customers. Answers are claims unless backed by Level 2 or another audit. Typical evidence is the completed CAIQ or the STAR Registry item. Do not treat a filled CAIQ as equivalent to SOC 2. SIG is a different questionnaire family from Shared Assessments; do not merge them.",
    lat=47.6062,
    lng=-122.3321,
    related=["csa-ccm", "csa-star-l1", "sig"],
    weight=3,
)

add(
    id="sig",
    name="SIG",
    short="SIG",
    family="questionnaires",
    kind="questionnaire",
    geography=["global"],
    industry=["all"],
    issuer="Shared Assessments",
    eli5="A standard vendor-security questionnaire used by a lot of banks and big companies. Completing it is homework, not a certificate.",
    elaborate="The Standardized Information Gathering questionnaire is published by Shared Assessments. Variants include SIG Core, SIG Lite, and topical modules (names have shifted across versions — read the version on the file). It is a questionnaire, not a certification. A completed SIG is evidence that someone answered questions, sometimes with attachments. It is not an independent audit unless a third party attested to the answers, which is uncommon. Typical evidence is the completed workbook dated and scoped to the product. CAIQ is the CSA cousin. Do not score a SIG as SOC 2. This register includes it because trust portals often list 'SIG available' as if it were a mark.",
    lat=35.6870,
    lng=-105.9378,
    related=["caiq", "cis-controls", "soc-2-type-ii"],
    weight=3,
)
