"""Clerk reading sentences for the Standards book.

One short plain sentence per mark: what the mark is evidence of,
and that it is not a company score and not a badge we issued.

Drawn from the existing ELI-5 / elaborate facts. Not legal advice.
NIST cite, if needed, is SP 1305 (C-SCRM quick-start: ask for evidence
before acquisition). This book names the mark. It does not issue it.
"""

READ = {
    "aiuc-1": "Evidence that a named AI agent was independently tested against a stated edition of the AIUC standard — not a company score, and not a badge we issued.",
    "bcr": "Evidence that a lead supervisory authority approved the group's binding internal transfer rules — not a company score, and not a badge we issued.",
    "c5": "Evidence of an independent auditor's C5 report against the BSI catalog — not a company score, and not a badge we issued.",
    "caiq": "Evidence that the provider published answers to CSA's questionnaire — not a company score, and not a badge we issued.",
    "ccpa-cpra": "Evidence, if any, is a privacy notice or contract term under California law; the statute is not a vendor certificate — not a company score, and not a badge we issued.",
    "cis-controls": "Evidence of a claimed mapping to CIS Controls, which anyone can adopt — not a company score, and not a badge we issued.",
    "cmmc-l1": "Evidence of a Level 1 self-assessment posted in SPRS for federal contract information — not a company score, and not a badge we issued.",
    "cmmc-l2": "Evidence of a CMMC Level 2 status against NIST SP 800-171 for CUI, when a current assessment exists — not a company score, and not a badge we issued.",
    "csa-ccm": "Evidence of a claimed mapping to CSA's Cloud Controls Matrix — not a company score, and not a badge we issued.",
    "csa-star-l1": "Evidence of a self-filled STAR Level 1 questionnaire on the CSA registry — not a company score, and not a badge we issued.",
    "csa-star-l2": "Evidence of a third-party STAR Level 2 audit listed in the CSA registry — not a company score, and not a badge we issued.",
    "cyber-essentials": "Evidence of a Cyber Essentials certificate against five basic UK hygiene controls — not a company score, and not a badge we issued.",
    "cyber-essentials-plus": "Evidence of a Plus certificate after an assessor tested those five controls — not a company score, and not a badge we issued.",
    "dora": "Evidence, if any, is a contract or disclosure under the EU operational-resilience law; DORA is not a vendor certificate — not a company score, and not a badge we issued.",
    "ens": "Evidence of an ENS certificate at a named level for Spanish government information — not a company score, and not a badge we issued.",
    "eprivacy": "Evidence, if any, is a notice or consent practice under the ePrivacy Directive; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "eu-ai-act": "Evidence, if any, is a statutory duty or conformity path under the EU AI Act; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "eu-us-dpf": "Evidence of a current listing on the Commerce Data Privacy Framework list — not a company score, and not a badge we issued.",
    "privacy-shield": "Evidence of nothing a buyer should accept: the adequacy decision was invalidated in 2020 — not a company score, and not a badge we issued.",
    "fedramp": "Evidence of a cloud offering listed on the FedRAMP Marketplace — not a company score, and not a badge we issued.",
    "fedramp-li-saas": "Evidence of a Tailored LI-SaaS Marketplace listing, not a Moderate or High authorization — not a company score, and not a badge we issued.",
    "fips-140-3": "Evidence of a CMVP certificate for a named cryptographic module and version — not a company score, and not a badge we issued.",
    "gdpr": "Evidence, if any, is a DPA or transfer tool; there is no GDPR vendor certificate — not a company score, and not a badge we issued.",
    "govramp": "Evidence of a product on the GovRAMP authorized-products list — not a company score, and not a badge we issued.",
    "hds": "Evidence of a French HDS certificate for hosting personal health data — not a company score, and not a badge we issued.",
    "hipaa": "Evidence, if any, is a BAA or an independent report that tested Security Rule controls; there is no official HIPAA certificate — not a company score, and not a badge we issued.",
    "hitrust-csf": "The CSF is a control library, not a certificate; evidence lives on the e1, i1, or r2 letter — not a company score, and not a badge we issued.",
    "hitrust-e1": "Evidence of a HITRUST e1 certification letter for a one-year essentials assessment — not a company score, and not a badge we issued.",
    "hitrust-i1": "Evidence of a HITRUST i1 certification letter for a one-year implemented assessment — not a company score, and not a badge we issued.",
    "hitrust-r2": "Evidence of a HITRUST r2 certification letter for a two-year risk-based assessment — not a company score, and not a badge we issued.",
    "irap": "Evidence of an IRAP assessor report against the Australian ISM, which an agency may accept — not a company score, and not a badge we issued.",
    "ismap": "Evidence of a cloud service listed on Japan's ISMAP register — not a company score, and not a badge we issued.",
    "iso-13485": "Evidence of an accredited certificate that a named medical-device quality system meets ISO 13485 — not a company score, and not a badge we issued.",
    "iso-22301": "Evidence of an accredited certificate that a named scope runs a business-continuity management system — not a company score, and not a badge we issued.",
    "iso-9001": "Evidence of an accredited certificate that a named scope runs a quality management system — not a company score, and not a badge we issued.",
    "iso-20000-1": "Evidence of an accredited certificate that a named scope runs an IT service management system — not a company score, and not a badge we issued.",
    "iso-27001": "Evidence of an accredited certificate that a named scope runs an information-security management system — not a company score, and not a badge we issued.",
    "iso-27017": "Evidence of cloud-security guidance applied with ISO 27001, not a stand-alone security certificate — not a company score, and not a badge we issued.",
    "iso-27018": "Evidence of cloud-privacy guidance applied with ISO 27001, not a GDPR certificate — not a company score, and not a badge we issued.",
    "iso-27701": "Evidence of an accredited certificate that a named scope runs a privacy information management system — not a company score, and not a badge we issued.",
    "iso-42001": "Evidence of an accredited certificate that a named scope runs an AI management system — not a company score, and not a badge we issued.",
    "k-isms": "Evidence of a Korean K-ISMS certificate for a named information-security management system — not a company score, and not a badge we issued.",
    "lgpd": "Evidence, if any, is a notice or contract under Brazil's LGPD; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "mtcs": "Evidence of a Singapore MTCS certificate at a named level — not a company score, and not a badge we issued.",
    "nis2": "Evidence, if any, is a national implementation duty under the NIS2 Directive; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "nist-ai-rmf": "Evidence of a claimed mapping to NIST's AI RMF; NIST issues no certificate — not a company score, and not a badge we issued.",
    "nist-csf": "Evidence of a claimed mapping to the CSF; NIST issues no CSF certificate — not a company score, and not a badge we issued.",
    "nist-800-171": "Evidence of a claimed or assessed 800-171 requirement set for CUI; NIST issues no 800-171 certificate — not a company score, and not a badge we issued.",
    "nist-800-53": "Evidence of a claimed baseline from the 800-53 catalog; NIST issues no 800-53 certificate — not a company score, and not a badge we issued.",
    "pci-3ds": "Evidence of a PCI 3DS assessment for systems that run 3-D Secure — not a company score, and not a badge we issued.",
    "pci-dss": "Evidence of a PCI DSS ROC or SAQ for cardholder-data scope — not a company score, and not a badge we issued.",
    "pci-ssf": "Evidence of a PCI SSF listing for payment software or a secure software lifecycle — not a company score, and not a badge we issued.",
    "pdpa-sg": "Evidence, if any, is a notice or contract under Singapore's PDPA; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "pdpa-th": "Evidence, if any, is a notice or contract under Thailand's PDPA; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "pipeda": "Evidence, if any, is a notice or contract under PIPEDA; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "sox": "Evidence, if any, is a public-company control opinion or a SOC 1 used by auditors; a private SaaS is not SOX certified — not a company score, and not a badge we issued.",
    "sig": "Evidence that the vendor completed a Shared Assessments SIG questionnaire — not a company score, and not a badge we issued.",
    "soc-1-type-i": "Evidence of a CPA's point-in-time SOC 1 report on financial-reporting controls — not a company score, and not a badge we issued.",
    "soc-1-type-ii": "Evidence of a CPA's period SOC 1 report on financial-reporting controls — not a company score, and not a badge we issued.",
    "soc-2-type-i": "Evidence of a CPA's point-in-time SOC 2 report on the design of in-scope Trust Services Criteria — not a company score, and not a badge we issued.",
    "soc-2-type-ii": "Evidence of a CPA's period SOC 2 report on operating effectiveness of in-scope Trust Services Criteria — not a company score, and not a badge we issued.",
    "soc-3": "Evidence of a general-use SOC 3 summary, not the restricted-use SOC 2 tests — not a company score, and not a badge we issued.",
    "soc-supply-chain": "Evidence of a CPA's SOC for Supply Chain report on a production or distribution system — not a company score, and not a badge we issued.",
    "scc": "Evidence of executed Standard Contractual Clauses as an Article 46 transfer tool — not a company score, and not a badge we issued.",
    "stateramp": "Evidence of a listing on the GovRAMP authorized-products list under the old StateRAMP name — not a company score, and not a badge we issued.",
    "swiss-us-dpf": "Evidence of a current Swiss-US Data Privacy Framework listing on the Commerce list — not a company score, and not a badge we issued.",
    "tisax": "Evidence of TISAX labels on the ENX portal after an approved assessment — not a company score, and not a badge we issued.",
    "tx-ramp": "Evidence of a TX-RAMP certification on the DIR certified-products list — not a company score, and not a badge we issued.",
    "us-state-privacy": "Evidence, if any, is a notice or contract under the named state statute; none of these laws issue a vendor certificate — not a company score, and not a badge we issued.",
    "uk-gdpr": "Evidence, if any, is a DPA or transfer tool under UK GDPR; it is not a vendor certificate — not a company score, and not a badge we issued.",
    "vcdpa": "Evidence, if any, is a notice or contract under Virginia's CDPA; it is not a vendor certificate — not a company score, and not a badge we issued.",
}
